### ISSUE TITLE
[Feature Request] iOS and Android support

### ISSUE THREAD

**Issue by ephemer** [modularml/max#107]
### What is your request?

I'd like to see MAX running on the edge, most importantly on iOS and Android

### What is your motivation for this change?

We have realtime, privacy-conscious use cases, so our ML deployments live exclusively at the edge, where performance is of utmost importance but for different reasons. Rather than optimizing for cost, we create versions of our models to maximize accuracy within the constraints of a number of device classes. I see huge potential for MAX in these areas.

**Comment by ehsanmok** [comment]
Today we’re on CPU, with GPU’s coming soon - you can see our [roadmap](https://docs.modular.com/max/roadmap). Stay tuned for any additional support!
