### ISSUE TITLE
[Feature Request] Wasm support

### ISSUE THREAD

**Issue by ephemer** [modularml/max#108]
### What is your request?

I'd like to see a version of MAX Engine running on Wasm

### What is your motivation for this change?

We have realtime, privacy-conscious use cases, so our ML deployments live exclusively at the edge, where performance is of utmost importance but for different reasons. Rather than optimizing for cost, we create versions of our models to maximize accuracy within the constraints of a number of device classes.

### Any other details?

Sorry for the double post with #107 but I imagine these two issues will be worked on and tracked separately.

**Comment by ehsanmok** [comment]
Today we’re on CPU, with GPU’s coming soon - you can see our [roadmap](https://docs.modular.com/max/roadmap). Stay tuned for any additional support!
