### ISSUE TITLE
[BUG]: Hanging Netron Visualizazion

### ISSUE THREAD

**Issue by suahelen** [modularml/max#116]
### Bug description

I was tinkering around with the following model.
https://github.com/openvinotoolkit/anomalib/tree/main/src/anomalib/models/image/fastflow

Running the model with the max engine seems to be fine as far as I can tell. Albeit, with the limited performance others have experienced on Windows so far.

When trying to visualize the graph with netron I get a warning that I am tring to visualize a model with a large number of nodes. Is that normal? When continuing the app hangs and does not seem to open the model. 
Visualizing the onnx file works fine.

### Steps to reproduce

Here are the models I used:
https://drive.google.com/drive/u/1/folders/17vKQe1kRtWYfkfJ5lflZc1-TIXniLobt

### System information

```shell
- What OS did you do install MAX on ?
> WSL Ubuntu

- Provide version information for MAX by pasting the output of max -v`
> max 24.1.0 (c176f84d)
- Provide version information for Mojo by pasting the output of mojo -v`
> mojo 24.1.0 (c176f84d)
- Provide Modular CLI version by pasting the output of `modular -v`
> Modular version 24.1.0-c176f84d-release
```

**Comment by ehsanmok** [comment]
That's normal in netron rendering large graphs. Please raise issues in [their repo](https://github.com/lutzroeder/netron/issues).

**Comment by suahelen** [comment]
I was more wodering about the reason why the Graph is much larger when I compile a model with MAX.

**Comment by ehsanmok** [comment]
Thanks! Just to confirm, the numbers you pasted above show that the torch_jit.maxviz is 41x (93395 / 2241) smaller than the original ONNX model. Can you provide more detail when you say the graph is larger? i.e. can you do a graph op or node dump here?

**Comment by suahelen** [comment]
Yes, I can confirm that the .maxviz is much smaller. 

With Graph I was referring to the visualization that netron would show. I guess it makes sense that this would be larger if you show the operations in more detail.

Thanks for the feedback.
