### ISSUE TITLE
[Feature Request] Windows support 

### ISSUE THREAD

**Issue by pharaohAi** [modularml/max#118]
### What is your request?

Windows support 

### What is your motivation for this change?

I use Windows. Windows is the most widely used operating system in the world. 69% of computer operating system users in the world use the Windows operating system. 

### Any other details?

Inform Mojo 🔥 users of the Windows support date, whether that is in a few months or years

**Comment by hogepodge** [comment]
Thanks for your interest. We understand that there's a lot of interest in Windows development, and it is on our roadmap. You can find the roadmap here. https://docs.modular.com/max/roadmap
