### ISSUE TITLE
 [Feature Request] support GPU 

### ISSUE THREAD

**Issue by pharaohAi** [modularml/max#119]
### What is your request?

support GPU 

### What is your motivation for this change?

GPU One of the most important components, if not the most important, for artificial intelligence computing requirements 

### Any other details?

Notify Mojo 🔥 users of a support appointment GPU Whether that is after a few months or years

**Comment by hogepodge** [comment]
Thanks for your interest. We understand that there's a lot of interest in GPU enablement, and it is on our roadmap. You can find more information in the roadmap here. https://docs.modular.com/max/roadmap
