### ISSUE TITLE
[Modular CLI]: libtinfo and curl problem

### ISSUE THREAD

**Issue by oldstager** [modularml/max#133]
### Issue description

**Issue encountered**

- Warning in *libtinfo* version information
- curl error (from inside modular)

**Expected to happen**

I can use modular without any issue to auth, install mojo, etc.

### Steps to reproduce

Using *modular*, I get the following warning and error:

```bash
modular auth
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: http error: failed to reach URL https://phoenix.modular.com/v1/oauth/device/authorize with cURL error Problem with the SSL CA cert (path? access rights?)
```

I tried to get json from shell using curl and it worked well:

```bash
$ curl https://packages.modular.com/mojo/1.root.json
{
 "signatures": [
  {
...
...
...
  },
  "spec_version": "1.0.31",
  "version": 1
 }
}
```

so, I think my local curl and modular server don't have any issues. Therefore, I suspect, something wrong with modular cli.

### Version Info

**Modular version**

```bash
$ modular -v
modular 0.6.0 (04c05243)
$
```

**OS Name**

```bash
$ uname -a
Linux alma 5.14.0-362.24.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 20 04:52:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
$
```

Distro:

```bash
$ cat /etc/redhat-release
AlmaLinux release 9.3 (Shamrock Pampas Cat)
$
```

**Comment by ehsanmok** [comment]
Thanks for trying MAX! We officially support MAX on Ubuntu. Please run the following and let us know if it helps the issue

```
sudo dnf update
sudo dnf install ncurses-libs
```

**Comment by oldstager** [comment]
unfortunately, the issue still persists after those commands.

**Comment by ehsanmok** [comment]
Thanks for reporting! As of today, Ubuntu is officially supported for MAX. Please check out the requirements [here](https://docs.modular.com/engine/get-started#requirements).

**Comment by oldstager** [comment]
ok, just tried because there's a *setup.rpm.sh* script, so I thought it will work on RHEL - derivatives system. thanks.
