### ISSUE TITLE
[BUG]: Cannot visualise an onnx model with Sub operand 

### ISSUE THREAD

**Issue by katrasnikj** [modularml/max#142]
### Bug description

When trying to visualise an onnx model I get the following error:

`error: 'mo.sub' op requires the same type for all operands and results`

The node looks like this:
![image](https://github.com/modularml/max/assets/2073561/1e8b797c-197b-429a-87b2-fd5876aaa58f)

### Steps to reproduce

max visualize model.onnx

### System information

```shell
modular 0.7.0 (487c2f88)
```

**Comment by ehsanmok** [comment]
Thanks for reporting! what version of `max -v` are you using?

**Comment by katrasnikj** [comment]
max 24.2.0 (c2427bc5)
Modular version 24.2.0-c2427bc5-release

**Comment by ehsanmok** [comment]
Thank you! could you share more about what type of model is having this issue and perhaps provide a reproducing example?

**Comment by iamtimdavis** [comment]
@katrasnikj - please let us know if you are facing issues and re-open this ticket, otherwise please try in 24.4. Thanks!
