### ISSUE TITLE
[Feature Request]  flatpak for linux?

### ISSUE THREAD

**Issue by jerin03** [modularml/max#144]
can you please make max sdk and release in flatpak also for linux, so other linux distro's(most known) can also have support for max sdk

**Comment by ehsanmok** [comment]
Please try our [new installer](https://docs.modular.com/max/get-started#1-install-magic) that should support the majorities on the linux distros.

**Comment by iamtimdavis** [comment]
Ill close this out - @jerin03, please re-open if you have an issue!
