### ISSUE TITLE
[BUG]: i can't install max sdk please can you check

### ISSUE THREAD

**Issue by jerin03** [modularml/max#145]
jki@fedora:~$ sudo modular install max
[sudo] password for jki: 
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
# Found release for https://packages.modular.com/max @ 24.2.1
# Resuming download of archive: /root/.modular/max-x86_64-unknown-linux-gnu-24.2.1-4-0.tar.gz
Downloaded   [ ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%   1.39GiB/1.39GiB             
# Extracting downloaded archives. 
Extracted    [ ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%   1.39GiB/1.39GiB             
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...
[mojo][error] Mojo SDK post-install test "`mojo build test_mandelbrot.mojo`" failed:
SubprocessError: Command '/root/.modular/pkg/packages.modular.com_max/bin/mojo build /root/.modular/pkg/packages.modular.com_max/test/test_mandelbrot.mojo -o /tmp/tmpl9eckrsx/test_mandelbrot' returned non-zero exit status 1.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 205, in test_mojo_build
    self.run_mojo(
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 193, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 181, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:
SubprocessError: Command '/root/.modular/pkg/packages.modular.com_max/bin/mojo build /root/.modular/pkg/packages.modular.com_max/test/test_python.mojo -o /tmp/tmpl9eckrsx/test_python' returned non-zero exit status 1.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 215, in test_mojo_build
    self.run_mojo(
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 193, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 181, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo repl`" failed:
SubprocessError: Command '/root/.modular/pkg/packages.modular.com_max/bin/mojo repl --one-line-before-file settings set target.load-cwd-lldbinit false --one-line-before-file settings set target.disable-aslr false --one-line-before-file settings set plugin.process.gdb-remote.packet-timeout 60' returned non-zero exit status 127.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /root/.modular/pkg/packages.modular.com_max/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 304, in test_mojo_repl
    raise SubprocessError(repl.returncode, " ".join(args), out, err)
[mojo][error] Mojo SDK post-install test "`mojo debug`" failed:
SubprocessError: Command ''/root/.modular/pkg/packages.modular.com_max/bin/mojo' 'debug' '-Xlldb' '--one-line-before-file' '-Xlldb' 'settings set target.load-cwd-lldbinit false' '-Xlldb' '--one-line-before-file' '-Xlldb' 'settings set target.disable-aslr false' '-Xlldb' '--one-line-before-file' '-Xlldb' 'settings set plugin.process.gdb-remote.packet-timeout 60' '-Xlldb' '-o' '-Xlldb' 'b test_debug.mojo:10' '-Xlldb' '-o' '-Xlldb' 'run' '-Xlldb' '-o' '-Xlldb' 'frame var foo' '-Xlldb' '-b' '/root/.modular/pkg/packages.modular.com_max/test/test_debug.mojo'' returned non-zero exit status 127.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /root/.modular/pkg/packages.modular.com_max/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 350, in test_mojo_debug
    raise SubprocessError(
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run script
==========================
Failure Information:
        - Script: `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin HOME=/root PYTHONPATH=/root/.modular/pkg/packages.modular.com_max/venv/lib/root/.modular/pkg/packages.modular.com_max/venv/bin/python /root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py --modular-home /root/.modular --package-path /root/.modular/pkg/packages.modular.com_max --mojo-config-section mojo-max`
        - Result: 1
        - Stderr:
[mojo][error] Mojo SDK post-install test "`mojo build test_mandelbrot.mojo`" failed:
SubprocessError: Command '/root/.modular/pkg/packages.modular.com_max/bin/mojo build /root/.modular/pkg/packages.modular.com_max/test/test_mandelbrot.mojo -o /tmp/tmpl9eckrsx/test_mandelbrot' returned non-zero exit status 1.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 205, in test_mojo_build
    self.run_mojo(
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 193, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 181, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:
SubprocessError: Command '/root/.modular/pkg/packages.modular.com_max/bin/mojo build /root/.modular/pkg/packages.modular.com_max/test/test_python.mojo -o /tmp/tmpl9eckrsx/test_python' returned non-zero exit status 1.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /usr/bin/ld: cannot find -ltinfo: No such file or directory
    collect2: error: ld returned 1 exit status
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: error: failed to link executable
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 215, in test_mojo_build
    self.run_mojo(
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 193, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 181, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo repl`" failed:
SubprocessError: Command '/root/.modular/pkg/packages.modular.com_max/bin/mojo repl --one-line-before-file settings set target.load-cwd-lldbinit false --one-line-before-file settings set target.disable-aslr false --one-line-before-file settings set plugin.process.gdb-remote.packet-timeout 60' returned non-zero exit status 127.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /root/.modular/pkg/packages.modular.com_max/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 304, in test_mojo_repl
    raise SubprocessError(repl.returncode, " ".join(args), out, err)
[mojo][error] Mojo SDK post-install test "`mojo debug`" failed:
SubprocessError: Command ''/root/.modular/pkg/packages.modular.com_max/bin/mojo' 'debug' '-Xlldb' '--one-line-before-file' '-Xlldb' 'settings set target.load-cwd-lldbinit false' '-Xlldb' '--one-line-before-file' '-Xlldb' 'settings set target.disable-aslr false' '-Xlldb' '--one-line-before-file' '-Xlldb' 'settings set plugin.process.gdb-remote.packet-timeout 60' '-Xlldb' '-o' '-Xlldb' 'b test_debug.mojo:10' '-Xlldb' '-o' '-Xlldb' 'run' '-Xlldb' '-o' '-Xlldb' 'frame var foo' '-Xlldb' '-b' '/root/.modular/pkg/packages.modular.com_max/test/test_debug.mojo'' returned non-zero exit status 127.
  stderr:
    /root/.modular/pkg/packages.modular.com_max/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /root/.modular/pkg/packages.modular.com_max/bin/mojo)
    /root/.modular/pkg/packages.modular.com_max/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
  File "/root/.modular/pkg/packages.modular.com_max/scripts/post-install/self-test.py", line 350, in test_mojo_debug
    raise SubprocessError(
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.

what can i do......

**Comment by ehsanmok** [comment]
Thanks for reporting! We currently only support Ubuntu and will later include more Linux distro like Fedora. Please check out the requirements [here](https://docs.modular.com/engine/get-started/#requirements)
