### ISSUE TITLE
[Feature Request] Support for Python 3.12

### ISSUE THREAD

**Issue by benz0li** [modularml/max#149]
### What is your request?

Please add wheels for Python 3.12.

### What is your motivation for this change?

TensorFlow 2.16.1 already supports Python 3.12:

* https://www.tensorflow.org/install/source#gpu

PyTorch 2.2 has experimental support for Python 3.12:

* https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

Ubuntu 24.04 LTS will also ship with Python 3.12.

### Any other details?

```bash
MAX_PATH=$(modular config max.path)
python3 -m pip install --find-links $MAX_PATH/wheels max-engine
```

```
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /home/benz0li/.modular/pkg/packages.modular.com_max/wheels
ERROR: Could not find a version that satisfies the requirement max-engine (from versions: none)
ERROR: No matching distribution found for max-engine
```

---

```bash
uname -a
python --version
ls /home/benz0li/.modular/pkg/packages.modular.com_max/wheels
```

```
Linux 692d72c4edff 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 x86_64 x86_64 GNU/Linux
Python 3.12.3
max_engine-24.2.1-cp310-cp310-linux_x86_64.whl  max_engine-24.2.1-cp39-cp39-linux_x86_64.whl
max_engine-24.2.1-cp311-cp311-linux_x86_64.whl  max_engine_libs-24.2.1-py3-none-linux_x86_64.whl
max_engine-24.2.1-cp38-cp38-linux_x86_64.whl
```

**Comment by benz0li** [comment]
@lattner Great to see a shift towards OSS with Mojo and MAX.

Is there a timeframe regarding support for Python 3.12?

Keep up the great work! Very much appreciated.

**Comment by ehsanmok** [comment]
Thanks for creating this feature request! It's planned but we don't have a fixed timeline yet. Stay tuned!

**Comment by benz0li** [comment]
PyTorch 2.4 will have full support for Python 3.12:

* https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix

**Comment by iamtimdavis** [comment]
Thanks @benz0li - we have this issue in the works and will be supporting 3.12 :)

**Comment by iamtimdavis** [comment]
I'll close this issue out, we've fixed this and it will ship in the next release (coming soon!)
