### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by imonem** [modularml/max#156]
### Where is the problem?

Claimed performance gains on Dell T3610

### What can we do better?

Same performance on a stock Dell&trade; T3610 *a bit old I know* but still performant.

I am reporting as you asked Dell&trade; T3610 Intel&reg; Xeon&reg; E5-1650 v2 32GB ECC memory Windows 11, WSL 2.0 Ubuntu 22.04 LTS Jammy everything else was according to [getting started](https://docs.modular.com/engine/get-started)

![H23nFWksaI](https://github.com/modularml/max/assets/28544605/ca65f72f-dfc6-4fcc-a1bb-f9f0d2b88f67)
_VS Code Terminal_

**Comment by ehsanmok** [comment]
Thanks for reporting! this is known limitation for low capable systems. Please see [this FAQ](https://docs.modular.com/engine/faq#why-does-max-engine-perform-slowly-on-my-computer-compared-to-pytorch) for more details.
