### ISSUE TITLE
Lower than expected performance improvement for PyTorch for roberta on X86-64

### ISSUE THREAD

**Issue by RonM-Dyalog** [modularml/max#161]
Your speed-up summary for Pytorch for roberta expected speedups of about 1.20x and my machine reported 0.96x.
Your UI asked me to report the details of the machine I'm running:

Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz   2.71 GHz
Ram: 16.0 GB
System type: 64-bit operating system, x64-based processor

Edition: Windows 10 Pro
Version: 22H2
Installed: 4/21/2021
OS build: 19045.4355

The test was run within the Windows WSL environment of Windows 10.

**Comment by ehsanmok** [comment]
Thanks for reporting! that's a known issue with low capable systems. Please see [this FAQ](https://docs.modular.com/engine/faq#why-does-max-engine-perform-slowly-on-my-computer-compared-to-pytorch).
