### ISSUE TITLE
[Docs] first example not work by require cmake 3.24 in ubuntu 22.04.3

### ISSUE THREAD

**Issue by dlintw** [modularml/max#163]
### Where is the problem?

https://docs.modular.com/engine/get-started#2-run-your-first-model

### What can we do better?

point out how to install newer cmake, or support more OS (eg. ubuntu 24.04 LTS which WSL2 support)

### Anything else?

I use WSL2 ubuntu

**Comment by dlintw** [comment]
my solution for ubuntu 22.04 is:

sudo snap install cmake

**Comment by ehsanmok** [comment]
The example in the doc refers to [bert-python-torchscript](https://github.com/modularml/max/tree/main/examples/inference/bert-python-torchscript) that only needs python dependencies. I think you're referring to [bert-c-torchscript](https://github.com/modularml/max/tree/main/examples/inference/bert-c-torchscript) which requires cmake.

**Comment by dlintw** [comment]
Yes, my mistake.

**Comment by ehsanmok** [comment]
Thanks and fixed! will be updated in the next release.
