### ISSUE TITLE
[BUG]: Using PyTorch in combination with MAX on macOS requires torch 2.2.2

### ISSUE THREAD

**Issue by goldiegadde** [modularml/max#165]
### Bug description

If you're on macOS and you want to use MAX Engine with a TorchScript model (or load both the torch and max Python packages), your torch version must be exactly 2.2.2. Otherwise, MAX Engine will crash when attempting to load your model.
We are working to resolve this and will update this issue as soon as we have more information.

### System information

```shell
- What OS did you do install MAX on ?
MacOS
- Provide version information for MAX by pasting the output of max -v`
MAX nightly starting 5/16
 
- Provide Modular CLI version by pasting the output of `modular -v`
v0.8
```

**Comment by iamtimdavis** [comment]
I'll close this issue out, we've fixed this in the next release (coming soon!)
