### ISSUE TITLE
[Modular CLI]: max/examples/inference/bert-python-torchscript

### ISSUE THREAD

**Issue by Alteglatze** [modularml/max#167]
### Issue description

I installed Max to learn max.
I'm attempting to run max/examples/inference/bert-python-torchscript/bash run,sh. I get the following error after updating settings with max, and pyramid_beaker:
  File "/hpome/sam/.local/lib/python3,10/site-packages/max/debug.py" line 4
        def patched_checkToken(url, username,token,scope, False):
                                                                                              ^^^^^
SyntaxError: invalid syntax

### Steps to reproduce

* Include relevant code snippet that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* Include anything else that might help us debug the issue.
  sam@rudi2:\~/max/examples/inference/bert-python-torchscript$ bash [run.sh](http://run.sh)
* INPUT_EXAMPLE='Paris is the \[MASK\] of France.'
* MODEL_PATH=../../models/bert-mlm.torchscript
  ++ dirname [run.sh](http://run.sh)
* cd .
* python3 ../common/bert-torchscript/download-model.py -o ../../models/bert-mlm.torchscript --mlm
  Downloading model...
  /home/sam/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
  Saving model in TorchScript format...
  '../../models/bert-mlm.torchscript' already exists.
* python3 [simple-inference.py](http://simple-inference.py) --text 'Paris is the \[MASK\] of France.' --model-path ../../models/bert-mlm.torchscript
  Traceback (most recent call last):
  File "/home/sam/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in
    from max import engine
  File "/home/sam/.local/lib/python3.10/site-packages/max/**init**.py", line 20, in
    from max import debug
  File "/home/sam/.local/lib/python3.10/site-packages/max/debug.py", line 4
    def patched_checkToken(url, username, token, scope, False):
                                                        ^^^^^
  SyntaxError: invalid syntax

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
sam@rudi2:~/max/examples/inference/bert-python-torchscript$ modular -v
modular 0.8.0 (39a426b5)
Ubuntu 22.04 LTS
```

**Comment by ehsanmok** [comment]
Thanks for reporting! What's the `max -v` you're using?

**Comment by ehsanmok** [comment]
I can't reproduce. Do you still have the issue?

**Comment by Alteglatze** [comment]
I'm having a problem with ubuntu updates, so that is where I think
the problem is.  Thanks for checking.

Sam

**Comment by stevew00ds** [comment]
I have same error on OSX

**Comment by stevew00ds** [comment]
max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release

**Comment by Sangrail** [comment]
Happens for me too on MacOS (Sonoma).

```
max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release
mojo 24.4.0 (59977802)
```

**Comment by ehsanmok** [comment]
I recommend to `modular clean` and install again see if it persists.

**Comment by iamtimdavis** [comment]
Please try again in 24.4 using our latest getting started instructions for `venv` or `conda` via https://docs.modular.com/max/install. Please re-open if you are still experiencing this issue.
