### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'max'

### ISSUE THREAD

**Issue by sonnysk98** [modularml/max#168]
### Bug description

While trying to run my first model as per get started documentation, I downloaded the bert-python-torchscript. Then while running inference, I get the error that Module not found.

### Steps to reproduce

* INPUT_EXAMPLE='Paris is the \[MASK\] of France.'
* MODEL_PATH=../../models/bert-mlm.torchscript
  ++ dirname [run.sh](http://run.sh)
* cd .
* python3 ../common/bert-torchscript/download-model.py -o ../../models/bert-mlm.torchscript --mlm
  Downloading model...
  config.json: 100%|██████████████████████████████████████████████████████████████████████| 570/570 \[00:00<00:00, 971kB/s\]
  model.safetensors: 100%|█████████████████████████████████████████████████████████████| 440M/440M \[03:38<00:00, 2.01MB/s\]
  Saving model in TorchScript format...
  Converting the model to TorchScript format...
  /home/sonnyuni/.local/lib/python3.10/site-packages/transformers/modeling_utils.py:4371: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
  Model saved.
* python3 [simple-inference.py](http://simple-inference.py) --text 'Paris is the \[MASK\] of France.' --model-path ../../models/bert-mlm.torchscript
  Traceback (most recent call last):
  File "/home/userx/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in
    from max import engine
  ModuleNotFoundError: No module named 'max'

### System information

```shell
OS: WSL Ubuntu 22.04
max 24.3.0 (9882e19d)
mojo 24.3.0 (9882e19d)
modular 0.8.0 (39a426b5)
```

**Comment by ehsanmok** [comment]
Thanks for reporting! Please make sure to follow all the steps in doc, particularly steps 5 and 6 [here](https://docs.modular.com/engine/get-started#1-install-the-max-sdk)

**Comment by ehsanmok** [comment]
Did following all the steps resolve the issue?

**Comment by OliverColeman** [comment]
Same for me. Fresh install (never installed before) on Ubuntu 22.04. 
I followed all the instructions at https://docs.modular.com/engine/get-started. 
* Stable version of modular CLI.
* Virtual env created with venv.
* Shell is zsh (I used the instructions for zsh to set environment variables) - I use oh-my-zsh if that makes any difference.

Running `max --version` outputs:
```                           
max 24.3.0 (9882e19d)
Modular version 24.3.0-9882e19d-release
```

**Comment by ehsanmok** [comment]
It looks like [step 5](https://docs.modular.com/max/install) is missing. Note that MAX cli is different from MAX python package.

```sh
MAX_PATH=$(modular config max.path) \
  && python3 -m pip install --find-links $MAX_PATH/wheels max-engine
```

**Comment by iamtimdavis** [comment]
Please try again in 24.4 using our latest getting started instructions for `venv` or `conda` via https://docs.modular.com/max/install. Please re-open if you are still experiencing this issue.
