### ISSUE TITLE
[BUG]: Error while installing MAX

### ISSUE THREAD

**Issue by Unknownuserfrommars** [modularml/max#171]
### Bug description

I'm using windows, and had a WSL (Ubuntu 22.04.3) installed. I also have the WSL connected to VSCode. In the VSCode terminal, i followed the installation manual until the "modular install max" part. when i entered it to my console, it came me an error:
(max-venv) user123@unknownuserfrommars:\~$ modular install max
modular: error: http error: failed to reach URL [https://packages.modular.com/max/1.root.json](https://packages.modular.com/max/1.root.json) with cURL error Timeout was reached

### Steps to reproduce

python3 -m venv max-venv && source max-venv/bin/activate

modular auth

modular install max

### System information

```shell
OS: Windows 11 23H2, Ubuntu WSL 22.04.3 LTS
Modular version:
modular 0.8.0 (39a425b5)
Mojo version:
None (Need i install mojo before max? That MAY be the problem)
max version:
None (Problem with installation)
```

**Comment by Unknownuserfrommars** [comment]
I COMPLETELY followed the instructions, from step 1 to 4 (where the error happened)

**Comment by ehsanmok** [comment]
Thanks for reporting! could you try again and see if it persists?

**Comment by Unknownuserfrommars** [comment]
No, the error persists, I've also tried 'modular install mojo', same error: modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Timeout was reached

**Comment by iamtimdavis** [comment]
Please try again in 24.4 using our latest getting started instructions for venv or conda via https://docs.modular.com/max/install. You can clean by running `modular clean` and/or update via https://docs.modular.com/max/update

Please re-open if you are still experiencing this issue.
