### ISSUE TITLE
[BUG]: Error when run script -> bash run.sh

### ISSUE THREAD

**Issue by stevew00ds** [modularml/max#176]
### Bug description

Saving model in TorchScript format...
'../../models/bert-mlm.torchscript' already exists.

+ python simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Traceback (most recent call last):
  File "/Users/stevewoods/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in <module>
    from max import engine
  File "/opt/miniconda3/envs/max/lib/python3.11/site-packages/max/__init__.py", line 20, in <module>
    from max import debug
  File "/opt/miniconda3/envs/max/lib/python3.11/site-packages/max/debug.py", line 4
    def patched_checkToken(url, username, token, scope, False):
                                                        ^^^^^
SyntaxError: invalid syntax

### Steps to reproduce

Execute all the "Getting Started" actions. Then run "bash run.sh"

### System information

```shell
- What OS did you do install MAX on ? OSX

max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release

mojo 24.4.0 (59977802)

modular 0.8.0 (39a426b5)
```

**Comment by ehsanmok** [comment]
Thanks for reporting however, I can't reproduce! It looks like the `max` package hasn't been installed correctly. In my

```sh
ls miniconda3/envs/py311/lib/python3.11/site-packages/max
```
shows

```sh
engine  lib
```
and there's no `max/init.py` or `max/debug.py`. I suggest to `modular clean` and follow _all_ the steps [here](https://docs.modular.com/max/install#install-max). We will soon refine the installation process so stay tuned for that!

Here's the `bash run.sh` log after `python3 -m pip install -r requirements.txt` in `examples/inference/bert-python-torchscript/`

```sh
bash run.sh 
+ INPUT_EXAMPLE='Paris is the [MASK] of France.'
+ MODEL_PATH=../../models/bert-mlm.torchscript
++ dirname run.sh
+ cd .
+ python3 ../common/bert-torchscript/download-model.py -o ../../models/bert-mlm.torchscript --mlm
Downloading model...
/Users/ehsan/miniconda3/envs/py311/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Saving model in TorchScript format...
Converting the model to TorchScript format...
/Users/ehsan/miniconda3/envs/py311/lib/python3.11/site-packages/transformers/modeling_utils.py:4371: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
Model saved.
+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Compiling model..   
Done!
/Users/ehsan/miniconda3/envs/py311/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Processing input...
Input processed.

input text: Paris is the [MASK] of France.
filled mask: Paris is the capital of France.
```

**Comment by andre-artus** [comment]
I'm having the same issue on Ubuntu 24.04 on WSL. 
I'm running python3.11 through venv as described in the docs.
```
> python -V
Python 3.11.9
```

```
> max --version
max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release
```

```
>  bash run.sh
+ INPUT_EXAMPLE='Paris is the [MASK] of France.'
+ MODEL_PATH=../../models/bert-mlm.torchscript
++ dirname run.sh
+ cd .
+ python3 ../common/bert-torchscript/download-model.py -o ../../models/bert-mlm.torchscript --mlm
Downloading model...
~/max-venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Saving model in TorchScript format...
'../../models/bert-mlm.torchscript' already exists.

+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Traceback (most recent call last):
  File "/mnt/d/source/mojo/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in <module>
    from max import engine
ModuleNotFoundError: No module named 'max`
```

**Comment by ehsanmok** [comment]
You are probably missing the [step 5](https://docs.modular.com/max/install#install-max) in your venv. Note that max CLI is different from its Python library.

**Comment by andre-artus** [comment]
> You are probably missing the [step 5](https://docs.modular.com/max/install#install-max) in your venv. Note that max CLI is different from its Python library.

Thanks. That did the trick. Not sure how I missed it.
