### ISSUE TITLE
[BUG]: FileNotFoundError: [Errno 2] No such file or directory: 'cpuinfo' when running performance showcase model

### ISSUE THREAD

**Issue by Ivo-Balbaert** [modularml/max#18]
### Bug description

I successfully installed MAX and ran the first model (§ 2) with the right output.

When running **3. Run the performance showcase**

step 1 ran without problem
sztep 2: 
$ python3 run.py -m roberta
Doing some one time setup. This takes 5 minutes or so, depending on the model.
Get a cup of coffee and we'll see you in a minute!

Compiling model.    a testing...[33%]
Done!
Done! [100%]

Starting inference throughput comparison

----------------------------------------System Info----------------------------------------

Traceback (most recent call last):
  File "/home/ivo/max/examples/performance-showcase/run.py", line 46, in <module>
    subprocess.run(["cpuinfo", "-g"])
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cpuinfo'

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

Here is the output from the two steps in 3. Run the performance showcase:

ivo@megaverse:~/max/examples$ cd performance-showcase/
ivo@megaverse:~/max/examples/performance-showcase$ python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (9.0.1)
Requirement already satisfied: tensorflow in /home/ivo/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.15.0.post1)
Requirement already satisfied: transformers in /home/ivo/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (4.38.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (1.25.2)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from tensorflow->-r requirements.txt (line 2)) (21.3)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (1.60.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (2.15.2)
Requirement already satisfied: h5py>=2.9.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (3.10.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (0.36.0)
Requirement already satisfied: flatbuffers>=23.5.26 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (23.5.26)
Requirement already satisfied: google-pasta>=0.1.1 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: termcolor>=1.1.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (3.3.0)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (0.5.4)
Requirement already satisfied: absl-py>=1.0.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: ml-dtypes~=0.2.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (2.15.0)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: libclang>=13.0.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (16.0.6)
Requirement already satisfied: astunparse>=1.6.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (1.6.3)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (4.25.3)
Requirement already satisfied: setuptools in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (69.1.0)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (2.15.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /home/ivo/.local/lib/python3.10/site-packages (from tensorflow->-r requirements.txt (line 2)) (4.8.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers->-r requirements.txt (line 3)) (5.4.1)
Requirement already satisfied: regex!=2019.12.17 in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (2023.12.25)
Requirement already satisfied: safetensors>=0.4.1 in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (0.4.2)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (0.15.2)
Requirement already satisfied: filelock in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (3.13.1)
Requirement already satisfied: tqdm>=4.27 in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (4.66.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (0.20.3)
Requirement already satisfied: requests in /home/ivo/.local/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow->-r requirements.txt (line 2)) (0.37.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home/ivo/.local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers->-r requirements.txt (line 3)) (2024.2.0)
Requirement already satisfied: markdown>=2.6.8 in /home/ivo/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (3.5.2)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /home/ivo/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/ivo/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (0.7.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/ivo/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: werkzeug>=1.0.1 in /home/ivo/.local/lib/python3.10/site-packages (from tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ivo/.local/lib/python3.10/site-packages (from requests->transformers->-r requirements.txt (line 3)) (2.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ivo/.local/lib/python3.10/site-packages (from requests->transformers->-r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ivo/.local/lib/python3.10/site-packages (from requests->transformers->-r requirements.txt (line 3)) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in /home/ivo/.local/lib/python3.10/site-packages (from requests->transformers->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/ivo/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/ivo/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/ivo/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (5.3.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/ivo/.local/lib/python3.10/site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/ivo/.local/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/ivo/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow->-r requirements.txt (line 2)) (3.2.0)

ivo@megaverse:~/max/examples/performance-showcase$ python3 run.py -m roberta
Doing some one time setup. This takes 5 minutes or so, depending on the model.
Get a cup of coffee and we'll see you in a minute!

Compiling model.    a testing...[33%]
Done!
Done! [100%]

Starting inference throughput comparison

----------------------------------------System Info----------------------------------------

Traceback (most recent call last):
  File "/home/ivo/max/examples/performance-showcase/run.py", line 46, in <module>
    subprocess.run(["cpuinfo", "-g"])
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cpuinfo'

### System information

```shell
- What OS did you do install MAX on ?  WSL2 (in Windows 11) which runs Ubuntu 22 
- Provide version information for MAX by pasting the output of max -v`

max 24.1.0-beta1 (f7ed1b63)
Modular version 24.1.0-beta1-f7ed1b63-release

Command works only from folder /home/user/.modular/pkg/packages.modular.com_beta_max/bin

- Provide version information for Mojo by pasting the output of mojo -v`  mojo 0.7.0 (af002202)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.5.0 (47924ae4)
```

**Comment by goldiegadde** [comment]
Thanks @Ivo-Balbaert for the issue, can you comment out the cpuinfo line for now and run, we will fix it shortly

**Comment by Ivo-Balbaert** [comment]
Thanks @goldiegadde  for the quick response.
After commenting out the line 

subprocess.run(["cpuinfo", "-g"])

in run.py

all runs well. Thank you!

**Comment by iamtimdavis** [comment]
@sparadiso can you take a look?
