### ISSUE TITLE
[BUG]: Max Serve Deploy.sh WSL Port Issue

### ISSUE THREAD

**Issue by anthony-chaudhary** [modularml/max#181]
### Bug description

Following https://docs.modular.com/max/serve/get-started `bash deploy.sh`
does not appear to work on WSL 2.

Screenshot below shows the sleep operation keeps waiting. Manually running the health check shows connection refused. Showing port list it shows no ports.

![image](https://github.com/modularml/max/assets/18080164/bdbc60db-41dd-4d8d-9db1-69f93e5f31e5)

This issue was resolved by replacing the docker run command in deploy.sh ` --net=host` with
```
-p 8000:8000 -p 8001:8001 -p 8002:8002   ...
```

While this did solve it, I haven't specifically submitted a pull request given the trade offs involved. This issue seemed related/relevant https://github.com/docker/for-win/issues/6736

### Steps to reproduce

Follow instructions from https://docs.modular.com/max/serve/get-started with the system info mentioned in other sections
![image](https://github.com/modularml/max/assets/18080164/4652ad11-40e2-4ead-a19c-a55f380567ae)

### System information

```shell
- WSL 2
- Latest image `public.ecr.aws/modular/max-serving-de:latest`
- Instructions from https://docs.modular.com/max/serve/get-started
- Last commit SHA f2f49795d6f27039d24c14d92168c7892c3b2b49
- https://github.com/modularml/max/blob/main/examples/inference/bert-python-torchscript/deploy.sh
```

**Comment by iamtimdavis** [comment]
@alexandrnikitin - are you able to take a look? Thx

**Comment by navroopbath** [comment]
Thanks for reporting this! We will fix the port exposing issue for WSL in the deploy.sh in the upcoming release.
