### ISSUE TITLE
[Docs] Max Serve - Prompt example is out of date

### ISSUE THREAD

**Issue by anthony-chaudhary** [modularml/max#183]
### Where is the problem?

The example is out of sync with code

### What can we do better?

https://docs.modular.com/max/serve/get-started

```
python3 max/examples/inference/bert-python-torchscript/triton-inference.py \
  --text "Paris is the [MASK] of France."
```

`  --text` was replaced by `--input` https://github.com/modularml/max/pull/154/files#diff-9912081dd60020f4d37e401adc5f1ab3e44268753442f39c7bbee73ddeb9daa0R60

**Comment by iamtimdavis** [comment]
@navroopbath - PTAL 🙇

**Comment by hogepodge** [comment]
Fixed upstream. Thanks for the report!
