### ISSUE TITLE
[Feature Request] Add support for Google Colab

### ISSUE THREAD

**Issue by anthony-chaudhary** [modularml/max#184]
### Where is the problem?

There was no colab example

### What can we do better?

Created a colab example here https://colab.research.google.com/drive/1Y2pJFwOm-v94sC6ivutmeitnRJixffhS#scrollTo=qJMfX-w5aKAX

This adds the following blocks
```
!curl -s https://get.modular.com | sh -
!modular auth
!modular install max
```
Edit: I was playing with having it add to path but not quite there yet:
```
%%bash

# Set the MODULAR_HOME environment variable
echo 'export MODULAR_HOME="/root/.modular"' >> ~/.bashrc

# Get the MAX_PATH
MAX_PATH=$(modular config max.path)

# Add MAX_PATH to the PATH environment variable
echo 'export PATH="'$MAX_PATH'/bin:$PATH"' >> ~/.bashrc

# Source the bashrc to apply changes
source ~/.bashrc

# Print the updated PATH to verify
echo "Updated PATH: $PATH"
```
![image](https://github.com/modularml/max/assets/18080164/267e7189-df0a-475a-97c4-7b3f06d0b439)

The goal is to be able to try this out by using colab and clicking run-all without any further thought.

The manual URL auth step is still required and not documented in the linked example

**Comment by iamtimdavis** [comment]
Will close this in favor of #223
