### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'max'

### ISSUE THREAD

**Issue by odhiambo123** [modularml/max#185]
### Bug description

attempting to run steps 2 of "Run your first model"    : bash run.sh

using anaconda 
I get a ModuleNotFound error. please see the terminal output below.`warnings.warn(
config.json: 100%|██████████████████████████████| 570/570 [00:00<00:00, 834kB/s]
model.safetensors: 100%|█████████████████████| 440M/440M [00:11<00:00, 40.0MB/s]
Saving model in TorchScript format...
Converting the model to TorchScript format...
/opt/anaconda3/envs/max/lib/python3.11/site-packages/transformers/modeling_utils.py:4371: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
Model saved.
+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Traceback (most recent call last):
  File "/Users/odhis926/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in <module>
    from max import engine
ModuleNotFoundError: No module named 'max'`

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install MAX on ? macOS Sonoma
- Provide version information for MAX by pasting the output of max -v` zsh: command not found: max
- Provide version information for Mojo by pasting the output of mojo -v` zsh: command not found: mojo
- Provide Modular CLI version by pasting the output of `modular -v`0.8.0
```

**Comment by odhiambo123** [comment]
successfully succeeded after reinstall

**Comment by ehsanmok** [comment]
Thanks
