### ISSUE TITLE
[BUG]: Image redirect in docs

### ISSUE THREAD

**Issue by b0llull0s** [modularml/max#187]
HI there is a weird redirect on the emoji from mojo
![image](https://github.com/modularml/max/assets/128314429/2f3144ba-40f1-48ef-8142-4ae3d49904ae)

Its here!
![swappy-20240705-011029](https://github.com/modularml/max/assets/128314429/e9dc44bd-1d7c-4c5f-bc73-8c7437ccfd22)

**Comment by b0llull0s** [comment]
I dont want to do anything, but i dont think its safe to be in /mojo just be clicking the emoji

**Comment by ehsanmok** [comment]
Thanks for reporting! good catch.

**Comment by iamtimdavis** [comment]
@scottamain can you please fix! thanks

**Comment by b0llull0s** [comment]
Hello!

I'm happy to help If you guys allow me to test; so this way I could give a more helpful report and who knows maybe find something else!
