### ISSUE TITLE
example MAX fail

### ISSUE THREAD

**Issue by dgarza31** [modularml/max#195]
last error lines:

/Users/danagarza/max-venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Saving model in TorchScript format...
'../../models/bert-mlm.torchscript' already exists.

+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Traceback (most recent call last):
  File "/Users/danagarza/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in <module>
    from max import engine
  File "/Users/danagarza/max-venv/lib/python3.11/site-packages/max/__init__.py", line 20, in <module>
    from max import debug
  File "/Users/danagarza/max-venv/lib/python3.11/site-packages/max/debug.py", line 4
    def patched_checkToken(url, username, token, scope, False):
                                                        ^^^^^
SyntaxError: invalid syntax

**Comment by dgarza31** [comment]
check your example

**Comment by ehsanmok** [comment]
Thanks! similar has been reported before. Please check out #167 and #176 and let us know if the solutions didn't work for you.

**Comment by ehsanmok** [comment]
Please feel free to reopen if non worked.
