### ISSUE TITLE
[Modular CLI]: MAX llama3 example fails

### ISSUE THREAD

**Issue by antonl321** [modularml/max#196]
### Issue description

I have followed he instruction to install/upgrade MAX and mojo, then I tried to run the max examples, the llama3 fails with the errors shown in the next window.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.
 mojo ../../run_pipeline.🔥 llama3 --prompt "I believe the meaning of life is"
Included from /home/syla/Apps/MAX/max/examples/graph-api/pipelines/llama3/../../run_pipeline.🔥:16:
/home/syla/Apps/MAX/max/examples/graph-api/pipelines/llama2/run.🔥:278:8: error: 'Path' does not implement the '__bool__' method
    if not config.get("model-path")[Path]:
       ^
Included from /home/syla/Apps/MAX/max/examples/graph-api/pipelines/llama3/../../run_pipeline.🔥:17:
/home/syla/Apps/MAX/max/examples/graph-api/pipelines/llama3/run.🔥:271:8: error: 'Path' does not implement the '__bool__' method
    if not config.get("model-path")[Path]:
       ^
Included from /home/syla/Apps/MAX/max/examples/graph-api/pipelines/llama3/../../run_pipeline.🔥:18:
/home/syla/Apps/MAX/max/examples/graph-api/pipelines/quantize_tinystories/run.🔥:17:57: error: package 'checkpoint' does not contain 'read_version'
.....

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
   modular 0.8.0 (39a426b5)
- What OS did you install modular CLI on ?
  WSL2 Ubuntu 22.04.3 LTS
```

**Comment by ehsanmok** [comment]
Please show the output of `max -v` too. Also please make sure you follow all the 5 steps [here](https://docs.modular.com/max/install).

**Comment by antonl321** [comment]
I have reinstalled the whole thing (max + mojo) carefully . 
The error persists.

max -v
max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release

The error seems "right", i.e. the compiler has can't bool a Path type, please see the test from below
```
  2> from pathlib import Path
  3.
  3> a=Path("foo")
  4.
(Path) a = {
  (String) path = "foo"
}
  4> if a : print("ok")
  5.
[User] error: Expression [5]:1:4: 'Path' does not implement the '__bool__' method
if a : print("ok")
   ^

expression failed to parse (no further compiler diagnostics)
 
  4>
  5> if a.exists() : print("ok")
  6> if not a.exists() : print("ok")
ok
```

**Comment by ehsanmok** [comment]
Thanks! Yes, Mojo's `Path` can't implicitly be converted to boolean which is unlike python if you meant. However, I can't reproduce the original llama3 issue either on Ubuntu or MacOS. Any chances you've max nightly installed (if you do please `modular clean`) or added something to the code? 

On

```
max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release
```
and 

```
mojo ../../run_pipeline.🔥 llama3 --prompt "I believe the meaning of life is"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1173  100  1173    0     0   1232      0 --:--:-- --:--:-- --:--:--  1232
100 4692M  100 4692M    0     0  19.4M      0  0:04:01  0:04:01 --:--:-- 20.0M
Loading tokenizer...
Building model...
Compiling...
Executing...
<|begin_of_text|>I believe the meaning of life is to find your purpose and passion, and to pursue it with intention and dedication. It's not about achieving some arbitrary goal or accumulating wealth, but about living a life that is authentic and meaningful to you.
For me, that means using my skills and talents to make a positive impact on the world. I believe that everyone has a unique gift or talent that they can use to make a difference, and I encourage others to find their own purpose and passion.
It's not always easy, and there will be challenges along the way. But I believe that the journey of finding your purpose and pursuing your passion is worth it, because it's a path that can bring joy, fulfillment, and a sense of purpose to your life.
I hope that my story can inspire others to find their own purpose and passion, and to pursue it with intention and dedication. I believe that we all have the power to create the life we want, and I hope that my story can help others to find their own path to fulfillment. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found my purpose and passion here: [link to your story]. Read more about my story and how I found
```

**Comment by antonl321** [comment]
Yes, my example were from the nightly build but is the max stable version ( I read too fast the instructions).
It looks fine now. Thanks!

**Comment by ehsanmok** [comment]
Thanks for verifying!
