### ISSUE TITLE
Run Yolov5 model in Max engine using Mojo

### ISSUE THREAD

**Issue by AryaMedapati** [modularml/max#201]
Issues in loading and compiling the yolov5s.torchscript model in MAX Engine using Mojo. Referred the documents at https://docs.modular.com/max/mojo/get-startedand https://docs.modular.com/max/model-formats, was not able to load the yolov5s model to perform object detection. Also tried loading the model by referring to the recent published article https://www.modular.com/blog/bring-your-own-pytorch-model leading to no success.

```
# Import necessary modules from MAX Engine
from max.engine import InputSpec, InferenceSession
from python import Python
from tensor import TensorSpec

def main():
	transformers = Python.import_module("transformers")
	batch = 1
	seqlen = 128

	input_ids_spec = TensorSpec(DType.int64, batch, seqlen)
	token_type_ids_spec = TensorSpec(DType.int64, batch, seqlen)
	attention_mask_spec = TensorSpec(DType.int64, batch, seqlen)
	input_specs = List[InputSpec]()

	input_specs.append(input_ids_spec)
	input_specs.append(attention_mask_spec)
	input_specs.append(token_type_ids_spec)
	# Specify the path to your TorchScript model file
	model_path = "bert-mlm.torchscript"

	# Create an instance of InferenceSession
	session = InferenceSession()

	# Load the model
	model = session.load(model_path)

	# Print model information (optional)
	print("Model loaded successfully.")

	INPUT=String("Paris is the [MASK] of France.")
	tokenizer = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")

	# Get the maximum sequence length from the model's output metadata
	output_spec = model.get_model_output_metadata()[0]
	max_seqlen = output_spec[1].value()[]

	# Tokenize the input text
	inputs = tokenizer(text=INPUT, add_special_tokens=True, padding="max_length", truncation=True, max_length=max_seqlen, return_tensors="np")

	input_ids = inputs["input_ids"]
	token_type_ids = inputs["token_type_ids"]
	attention_mask = inputs["attention_mask"]

	# Now we can run inference
	outputs = model.execute("input_ids", input_ids, "token_type_ids", token_type_ids, "attention_mask", attention_mask)

	logits = outputs.get[DType.float32]("result0")

	# Find the index of the mask token
	mask_idx = -1
	for i in range(len(input_ids[0])):
		if input_ids[0][i] == tokenizer.mask_token_id:
			mask_idx = i

	# Decode the predicted token
	predicted_token_id = logits.argmax()[mask_idx]
	decoded_result = tokenizer.decode(predicted_token_id, skip_special_tokens=True, clean_up_tokenization_spaces=True)

	print("input text: ", INPUT)
	print("filled mask: ", INPUT.replace("[MASK]", decoded_result))
```
Tried the above code and got the following error when running mojo user :~$ mojo load_model.mojo

Unhandled exception caught during execution: unable to convert PyTorch model: Could not load TorchScript model; please make sure to convert your PyTorch model to TorchScript before using MAX API.tls_on_entry.has_value() INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp":49, please report a bug to PyTorch.
Exception raised from pythonFallback at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:49 (most recent call first):
frame #0: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 192 (0x12d04d960 in libc10.dylib)
frame #1: c10::TypeError::~TypeError() + 0 (0x2ca2ab3d4 in libtorch_cpu.dylib)
frame #2: void c10::BoxedKernel::make_boxed_function<&(anonymous namespace)::pythonFallback(c10::OperatorHandle const&, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue>>*)>(c10::OperatorKernel*, c10::OperatorHandle const&, c10::DispatchKeySet, std::__1::vector<c10::IValue, std::__1::allocator<c10::IValue>>*) + 596 (0x2ca551094 in libtorch_cpu.dylib)
frame #3: at::_ops::empty_memory_format::call(c10::ArrayRef<c10::SymInt>, std::__1::optional<c10::ScalarType>, std::__
mojo: error: execution exited with a non-zero result: 1

How can we convert it to a PyTorch model when dependencies like torch are not available in mojo?

**Comment by ehsanmok** [comment]
Hi there! Please see the [docs](https://docs.modular.com/max/mojo/get-started#define-input-specs-torchscript-only). Meanwhile here the [yolo example using MAX Engine Python API](https://github.com/modularml/max/tree/main/examples/inference/yolo-python-onnx).

**Comment by ZolotukhinM** [comment]
This likely is caused by a non-supported version of torch installed on your system. We currently only support `2.2.2` (and cpuonly, i.e. without cuda). You can check the version with `pip` or by running the following command: `python -c "import torch; print(torch.__version__)"`.<br>We realize that it might be quite inconvenient, and are working on lifting this limitation in upcoming releases.
