### ISSUE TITLE
[Modular CLI]: Can't install Modular CLI

### ISSUE THREAD

**Issue by oseymour** [modularml/max#202]
### Issue description

I'm following the instructions [here](https://docs.modular.com/max/install) to get MAX installed on a SageMaker instance.

I ran the command in step 1 and got the following output:
![Note to self - 2024-08-14 11_48_42](https://github.com/user-attachments/assets/db521e9f-8211-4615-b075-b65c2773b1d2)

It shows an error but it also looks like it might have worked so I tried `modular install max` and got a "modular command not found" error.

### Steps to reproduce

```
$ curl -s https://get.modular.com | sh -s -- 72cc8ffc-f188-4760-8db2-6d58f468d359
$ modular install max
```

See screenshot above.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
    - Can't get version, "modular command not found"
- What OS did you install modular CLI on ?
    - Amazon Linux 2 (https://amazonlinux.com/)
```

**Comment by iamtimdavis** [comment]
Thanks @oseymour -> can you follow this: https://docs.modular.com/max/tutorials/deploy-cloudformation-sagemaker

Also, please join our discord and try our "magic-cli" tooling. This is going to replace Modular CLI very soon :) 

Feel free to re-open if you're having issues!
