### ISSUE TITLE
[Modular CLI]: modular: error: invalid manifest: root json is missing or invalid.

### ISSUE THREAD

**Issue by non-trivial0s** [modularml/max#203]
### Issue description

I followed [the tutorial](https://docs.modular.com/max/install) to install max on wsl2+ubuntu22.04 with python3.10
I ran 
~$ modular install max
and got 
"modular: error: invalid manifest: root json is missing or invalid."

### Steps to reproduce

$ curl -s https://get.modular.com | sh -s -- 4c102135-d538-4581-8e1b-42ead57dd21d
$ python3.10 -m venv ~/max-venv && source ~/max-venv/bin/activate
$ modular install max
modular: error: invalid manifest: root json is missing or invalid

### Version Info

```shell
- Modular CLI version 0.9.1(3460d12e)
```

**Comment by ehsanmok** [comment]
Thanks for reporting! This should be fixed by now. I'll leave it open until final confirmation.

**Comment by non-trivial0s** [comment]
Later I used
```
(max-venv) $ deactivate
$ sudo apt update && sudo apt upgrade -y
```
upgraded modular 0.9.1 (3460d12e) --> 0.9.2 (b3079bd5)
then
```
$ python3.10 -m venv ~/max-venv && source ~/max-venv/bin/activate
(max-venv) $ modular install max
```
still got 
"modular: error: invalid manifest: root json is missing or invalid."

**Comment by ehsanmok** [comment]
Can you run `modular clean` and install again?
