### ISSUE TITLE
[BUG]: Can't install MAX on Orange Pi platform

### ISSUE THREAD

**Issue by czyrsk** [modularml/max#204]
### Bug description

When I'm trying to install MAX Engine on Orange Pi platform i encounter problem below:
<img width="326" alt="image" src="https://github.com/user-attachments/assets/76ee0d72-f7d2-4b09-b286-14ae6f212cd5">
<img width="329" alt="image" src="https://github.com/user-attachments/assets/3bb58d7b-3e78-46c1-8ac0-cf89c15a646d">

During get-apt update i have this problem:
<img width="748" alt="image" src="https://github.com/user-attachments/assets/d3f1072e-1f1b-4a45-b56b-c65612b47043">
**“repository 'https://dl.modular.com/public/installer/deb/ubuntu focal InRelease' doesn't support architecture 'armhf’ ”.** 

Are you supporting Orange Pi ARM CPU architecture? Is there any workaround to install MAX Engine on Orange Pi platform?

### Steps to reproduce

- Prepare Orange Pi to installation MAX Engine
- Try to install MAX Engine

### System information

```shell
- What OS did you do install MAX on ?
Ubuntu 20.04
- Provide version information for MAX by pasting the output of max -v`
Can't check as max is not installed 
- Provide version information for Mojo by pasting the output of mojo -v`
Can't check as max is not installed 
- Provide Modular CLI version by pasting the output of `modular -v`
Can't check as max is not installed
```

**Comment by ehsanmok** [comment]
We currently support arm64 such as Graviton per the [requirements](https://docs.modular.com/max/install#requirements)
