### ISSUE TITLE
[Magic CLI]  Bash exits shell whether it is installed or not

### ISSUE THREAD

**Issue by DWSimmons** [modularml/max#210]
Whether or not bash has been added to the project, executing `Bash` command without options/args/filenames exits shell.  No error or logout given.

It does not matter whether bash has been added to the project.

```console
darin@home:/media/darin/M2/magic$ magic init bash_test
✔ Created /media/darin/M2/magic/bash_test/pixi.toml
darin@home:/media/darin/M2/magic$ cd bash_test/
darin@home:/media/darin/M2/magic/bash_test$ magic shell
 . "/tmp/pixi_env_ozq.sh"
darin@home:/media/darin/M2/magic/bash_test$  . "/tmp/pixi_env_ozq.sh"
(bash_test) darin@home:/media/darin/M2/magic/bash_test$ bash
darin@home:/media/darin/M2/magic/bash_test$ magic add bash
✔ Added bash >=5.2.21,<6
darin@home:/media/darin/M2/magic/bash_test$ magic shell
 . "/tmp/pixi_env_CVc.sh"
darin@home:/media/darin/M2/magic/bash_test$  . "/tmp/pixi_env_CVc.sh"
(bash_test) darin@home:/media/darin/M2/magic/bash_test$ bash
darin@home:/media/darin/M2/magic/bash_test$ magic shell
 . "/tmp/pixi_env_dE8.sh"
darin@home:/media/darin/M2/magic/bash_test$  . "/tmp/pixi_env_dE8.sh"
(bash_test) darin@home:/media/darin/M2/magic/bash_test$ vi hello.sh
(bash_test) darin@home:/media/darin/M2/magic/bash_test$ bash hello.sh 
Hello World
(bash_test) darin@home:/media/darin/M2/magic/bash_test$ bash
darin@home:/media/darin/M2/magic/bash_test$ 

```

Expected behavior:  Remain in shell.  Prints working directory as if in any normal terminal. 
For example
```console
(bash_test) darin@home:/media/darin/M2/magic/bash_test$ bash
(bash_test) darin@home:/media/darin/M2/magic/bash_test$
```

Actual behavior:  Exit shells.

I looked through the pixi issues and found nothing similar.  I have no idea if this has any reach to any other events or literally no scope so I opened an issue.

**Comment by ehsanmok** [comment]
Looks like you're creating a shell within a shell. This doesn't look like to be related to magic and is a [pixi issue](https://github.com/prefix-dev/pixi/issues). @zbowling please confirm.

**Comment by DWSimmons** [comment]
> Looks like you're creating a shell within a shell. This doesn't look like to be related to magic and is a [pixi issue](https://github.com/prefix-dev/pixi/issues). @zbowling please confirm.

I think you're right.  `exit` within the "bash shell" returns exit and puts me back into parent shell.


```console
darin@home:/media/darin/M2/magic/uniform$ magic shell
 . "/tmp/pixi_env_lrD.sh"
darin@home:/media/darin/M2/magic/uniform$  . "/tmp/pixi_env_lrD.sh"
(uniform) darin@home:/media/darin/M2/magic/uniform$ bash
darin@home:/media/darin/M2/magic/uniform$ 
darin@home:/media/darin/M2/magic/uniform$ exit
exit
(uniform) darin@home:/media/darin/M2/magic/uniform$ 
(uniform) darin@home:/media/darin/M2/magic/uniform$ exit
logout
```
I don't know what's actually happening under the hood, but it appears to be working intentionally; Closing.
