### ISSUE TITLE
[BUG]: Running 'bash run.sh' fails with error.

### ISSUE THREAD

**Issue by GaryLuck** [modularml/max#212]
### Bug description

gary5@Gary:~/max/examples/inference/bert-python-torchscript$ bash run.
sh
+ INPUT_EXAMPLE='Paris is the [MASK] of France.'
+ MODEL_PATH=../../models/bert-mlm.torchscript
++ dirname run.sh
+ cd .
+ python3 ../common/bert-torchscript/download-model.py -o ../../models/bert-mlm.torchscript --mlm
Downloading model...
/home/gary5/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
config.json: 100%|███████████████████| 570/570 [00:00<00:00, 2.20MB/s]
model.safetensors: 100%|███████████| 440M/440M [00:10<00:00, 43.8MB/s]
Saving model in TorchScript format...
Converting the model to TorchScript format...
/home/gary5/.local/lib/python3.10/site-packages/transformers/modeling_utils.py:4371: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
Model saved.
+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Traceback (most recent call last):
  File "/home/gary5/max/examples/inference/bert-python-torchscript/simple-inference.py", line 14, in <module>
    from max import engine
ModuleNotFoundError: No module named 'max'
gary5@Gary:~/max/examples/inference/bert-python-torchscript$

### Steps to reproduce

Just follow the normal install for my machine running Ubuntu under WSL2 on Windows 11 machine:
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### System information

```shell
Linux Gary 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by GaryLuck** [comment]
If I do "source ~/max-venv/bin/activate" before running "bash run.sh" it works correctly.

**Comment by ehsanmok** [comment]
There's no issue here! the venv needs to be activated.
