### ISSUE TITLE
[Magic CLI]: magic cannot install python into magic's own pyproject.toml

### ISSUE THREAD

**Issue by guidorice** [modularml/max#225]
### Issue description

The magic docs suggest to refer to the pixi docs for more advanced usage. The pixi docs say

> We support two manifest formats: pyproject.toml and pixi.toml. In this tutorial, we will use the pyproject.toml format because it is the most common format for Python projects. (https://pixi.sh/latest/tutorials/python/)

OK let's go with the pyproject format, and  just try to install python. Then it raises

>  ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://
      hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection

See reproduce steps below:

### Steps to reproduce

```shell
$ mkdir foo
$ cd foo/
$ magic init --format pyproject
✔ Created /Users/guidorice/tmp/foo/pyproject.toml
$ magic add python
  × error updating pypi prefix
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: foo @ file:///Users/guidorice/tmp/foo
  ├─▶ Failed to build: `foo @ file:///Users/guidorice/tmp/foo`
  ╰─▶ Build backend failed to build wheel through `build_editable()` with exit status: 1
  ...
  ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://
      hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection
```

### Version Info

```shell
$ magic info
      Pixi version: 0.27.1
          Platform: osx-arm64
  Virtual packages: __unix=0=0
                  : __osx=14.6.1=0
                  : __archspec=1=m2
         Cache dir: /Users/guidorice/Library/Caches/rattler/cache
      Auth storage: /Users/guidorice/.rattler/credentials.json

Project
------------
              Name: foo
           Version: 0.1.0
     Manifest file: /Users/guidorice/tmp/foo/pyproject.toml
  Config locations: 
      Last updated: 13-09-2024 15:04:21

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge, https://conda.modular.com/max
  Dependency count: 1
      Dependencies: python
 PyPI Dependencies: foo
  Target platforms: osx-arm64
```
```

**Comment by ehsanmok** [comment]
`pyproject.toml` behaves differently from `mojoproject.toml` or `pixi.toml` and you can include things like `requires-python = ">= 3.11"` at the project level which make sense because it's for python project and not a dependency.

**Comment by guidorice** [comment]
Hmm, OK I see now that `requires-python = ">= 3.11"` was indeed already added by the init command. All I can say is that magic's support for pyproject file seems really incomplete. What is the possible benefit of ever using `magic init --format pyproject`. Cannot apparently do anything with it:

```
$ magic add pytest
  × error updating pypi prefix
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: foo @ file:///Users/guidorice/tmp/foo
  ├─▶ Failed to build: `foo @ file:///Users/guidorice/tmp/foo`
  ╰─▶ Build backend failed to build wheel through `build_editable()` with exit status: 1
  (same Value error as above)
```

**Comment by ehsanmok** [comment]
There was a known upstream issue in pixi that got fixed recently but we haven't pushed it for magic. For now, please use the setuptools in `pyproject.toml`

```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

**Comment by zbowling** [comment]
This should be fixed now!
