### ISSUE TITLE
[BUG]: Debug Mojo File fails in VS Code with `Connection shut down by remote side while waiting for reply to initial handshake packet`

### ISSUE THREAD

**Issue by rabainu** [modularml/max#227]
### Bug description

VS Code can no longer debug Mojo with the max 24.5 SDK installed with Magic CLI. Trying to run Debug Mojo File ends with the error message `Connection shut down by remote side while waiting for reply to initial handshake packet`. On the command line the debugger seems to work normally.

### Steps to reproduce

```
% magic init project --format mojoproject
% cd project 
% magic shell
% mojo -v
mojo 24.5.0 (e8aacb95)
% code (to launch VS Code)
```
- Install Mojo extension in VS Code (v24.5.0)
- Open up a Mojo file in VS Code
- Debug Mojo File (or F5)
- > Connection shut down by remote side while waiting for reply to initial handshake packet

### System information

```shell
- What OS did you do install MAX on ?

macOS 14.6.1 (23G93)

- Provide version information for MAX by pasting the output of max -v`

max 24.5.0 (e8aacb95)
Modular version 24.5.0

- Provide version information for Mojo by pasting the output of mojo -v`

mojo 24.5.0 (e8aacb95)

- Provide Modular CLI version by pasting the output of `modular -v`

zsh: command not found: modular
```

**Comment by ehsanmok** [comment]
Have you enabled "Mojo: Enable Magic SDK" in the vscode settings?

**Comment by rabainu** [comment]
Debugger has worked for me since VS Code extension 24.5.1 (18.9.2024) if I launch VS Code from terminal with magic shell activated. Stepping in standard library functions doesn't work yet, but I think that is a separate issue.

**Comment by walter-erquinigo** [comment]
This should have been fixed already. Let me know if it's broken.
