### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Amahseyn** [modularml/max#230]
Hi, I am mohammad and I am AI engineer working on developing a computer vision model. I am really interested in working with Mojo and creating a GitHub repo for AI models using Mojo and comparing the speed of Mojo against other languages but I think Mojo and Max are limited to Iranian, I tested different VPNs but I got the same problems, Do you have any solution for my problem. Best regards

**Comment by ehsanmok** [comment]
Hi Mohammad! could you tell us what errors do you get when trying to install MAX (that contains Mojo) from [these instructions](https://docs.modular.com/max/get-started#1-install-magic)?

**Comment by Amahseyn** [comment]
Thank you so much, Ehsan, I had an error with the internet last week but now it's okay.

**Comment by ehsanmok** [comment]
Good to know! thanks.
