### ISSUE TITLE
[Docs] Tiny change in https://docs.modular.com/max/tutorials/magic

### ISSUE THREAD

**Issue by marionegroponzi** [modularml/max#236]
### Where is the problem?

https://docs.modular.com/max/tutorials/magic

### What can we do better?

The page
https://docs.modular.com/max/tutorials/magic#step-5-use-a-nested-package
suggests running `magic run bash local/zero`

but that returns "local/zero: local/zero: cannot execute binary file"

The command should be changed to `magic run bash -c local/zero`.

### Anything else?

You're awesome!

**Comment by marionegroponzi** [comment]
Also, I believe the build command `magic run mojo build local/zero.mojo` cannot (?) work. It should instead be
```
cd local
magic run mojo build zero.mojo
```

**Comment by ehsanmok** [comment]
Thanks! good catch. Will fix in the doc.

**Comment by ehsanmok** [comment]
Will be fixed in the next release.
