### ISSUE TITLE
ImportError:  version `GLIBCXX_3.4.29' not found  when following instructions on Get started with MAX

### ISSUE THREAD

**Issue by ScottzCodez** [modularml/max#239]
## Here is my system info:  (removed info not needed)
me@i7Laptop:~/hello-magic$ uname -r
5.15.153.1-microsoft-standard-WSL2

(I can't figure out why the following is bold -- MD renderer bad? )
me@i7Laptop:~/hello-magic$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
 ------------------------------------
## Issue Description:
When following instructions   Get started with MAX   at   https://docs.modular.com/max/get-started
I get this error when running the step:  bash run.sh    here's the last bit of its output...
Model saved.
python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
Traceback (most recent call last):
  File "/home/me/hello-magic/max/examples/inference/bert-python-torchscript/simple-inference.py", line 21, in <module>
    from max import engine
  File "/home/me/hello-magic/max/examples/inference/bert-python-torchscript/.magic/envs/default/lib/python3.12/site-packages/max/engine/__init__.py", line 8, in <module>
    from max._engine.core import __version__
  File "/home/me/hello-magic/max/examples/inference/bert-python-torchscript/.magic/envs/default/lib/python3.12/site-packages/max/_engine/__init__.py", line 7, in <module>
    from .core import *
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/me/hello-magic/max/examples/inference/bert-python-torchscript/.magic/envs/default/lib/python3.12/site-packages/max/_engine/core.cpython-312-x86_64-linux-gnu.so)

**Comment by zoldaten** [comment]
i have the same error when tried to start on aarch64 - raspberry pi 4b:
```
Traceback (most recent call last):
  File "/home/pi/max/examples/inference/yolo-python-onnx/segment.py", line 27, in <module>
    from max.engine import InferenceSession
  File "/home/pi/.local/lib/python3.9/site-packages/max/engine/__init__.py", line 8, in <module>
    from max._engine.core import __version__
  File "/home/pi/.local/lib/python3.9/site-packages/max/_engine/__init__.py", line 7, in <module>
    from .core import *
ImportError: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/pi/.local/lib/python3.9/site-packages/max/_engine/core.cpython-39-aarch64-linux-gnu.so)
```

**Comment by walter-erquinigo** [comment]
@ehsanmok , this is another one of that kind.

**Comment by ehsanmok** [comment]
For the original issue, the [minimum required](https://docs.modular.com/max/faq) Ubuntu version is **22.04**. 

@zoldaten This could either bc the same version issue so would be great if you could create a new issue with the details of your system info included.

**Comment by abdulghani91** [comment]
I have the same error
when I run:
magic run serve --huggingface-repo-id modularai/llama-3.1

I get this error:
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/abdulghani/max/pipelines/python/.magic/envs/default/lib/python3.12/site-packages/max/_driver/core.cpython-312-x86_64-linux-gnu.so)

I am using ubuntu 20.04
did anyone solve this error?

**Comment by ehsanmok** [comment]
[The minimum required Ubuntu version is 22.04](https://docs.modular.com/max/faq/) so upgrading is the way to go!

Another thing you can try is to add the following manually to [`pixi.toml`](https://github.com/modular/max/blob/main/pipelines/python/pixi.toml)

```toml
[system-requirements]
linux = "4.4"
libc = { family = "glibc", version = "2.28" }
```

might need to adjust depending on the available linux kernel and glibc but isn't guaranteed to work.
