### ISSUE TITLE
[BUG]: Mojo formatter not working in VSCode (format on save)

### ISSUE THREAD

**Issue by omarelb** [modularml/max#243]
### Bug description

For a while now my auto format is not working anymore in the VScode extension (currently on nightly). I'm using `magic` as the environment manager.

Inspecting the `Mojo (nightly)` output tab logs, I see this:
```
["ERROR" - 15:59:41] Formatting error:
/bin/sh: /Users/me/Library/Application: No such file or directory
```

If I look into the driver paths I see for instance 
```
"driver_path": "/Users/me/Library/Application Support/Code/User/globalStorage/modular-mojotools.vscode-mojo-nightly/magic-data-home/envs/max/bin/mojo",
```

So I suspect that the space in the Application Support folder (used by default on MacOS)  is messing up the invocation of mojo (or something in that vein). Any way I can fix this in the meantime?

### Steps to reproduce

Install nightly mojo with magic. Install the nightly vscode extension. Run `Format document` in vscode.

### System information

```shell
- What OS did you do install MAX on ?

MacOS 14.5 (Apple M2)

- Provide version information for MAX by pasting the output of max -v`

max 2024.10.2005 (f4489c54)
Modular version 2024.10.2005

Note: this is the version of the max binary used by the vscode extension (I believe).

- Provide version information for Mojo by pasting the output of mojo -v`

mojo 2024.10.2005 (f4489c54)

- Provide Modular CLI version by pasting the output of `modular -v`

N/A
```

**Comment by walter-erquinigo** [comment]
@omarelb , thank you for reporting! I'll take a look now.

**Comment by walter-erquinigo** [comment]
This should be fixed now on VSCode

**Comment by omarelb** [comment]
Works now, thank you!
