### ISSUE TITLE
[BUG]: simple-inference getting started example gives a runtime error

### ISSUE THREAD

**Issue by scottwarnick** [modularml/max#246]
### Bug description

modeling_utils.py:4371: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
Model saved.
+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
run.sh: line 33: 15827 Illegal instruction     (core dumped) python3 simple-inference.py --text "$INPUT_EXAMPLE" --model-path "$MODEL_PATH"

The expected result is Paris is the capital of France

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
See the error referenced above

- If applicable, add screenshots to help explain the problem.
See the error referenced above. 

- Include anything else that might help us debug the issue.
It looks like the script is referencing deprecated code. The script and the Getting Started documents need to be updated. 

### System information

```shell
- What OS did you do install MAX on ?
Linux mint
BERT Python Torchscript) root@mintdmhs:/home/warnicksm/max/examples/inference/bert-python-torchscript# cat /etc/issue
Linux Mint 22 Wilma \n \l


- Provide version information for MAX by pasting the output of max -v`
BERT Python Torchscript) root@mintdmhs:/home/warnicksm/max/examples/inference/bert-python-torchscript# max -v
max 24.5.0 (e8aacb95)
Modular version 24.5.0

- Provide version information for Mojo by pasting the output of mojo -v`
BERT Python Torchscript) root@mintdmhs:/home/warnicksm/max/examples/inference/bert-python-torchscript# max -v
max 24.5.0 (e8aacb95)
Modular version 24.5.0

- Provide Modular CLI version by pasting the output of `modular -v`
BERT Python Torchscript) root@mintdmhs:/home/warnicksm/max/examples/inference/bert-python-torchscript# max -v
max 24.5.0 (e8aacb95)
Modular version 24.5.0
```

**Comment by ehsanmok** [comment]
Please [install the magic](https://docs.modular.com/magic/) and run the examples using it. We no longer support Modular cli which is going to be deprecated soon.
