### ISSUE TITLE
Problem with downloading the Max 24.1.0-beta

### ISSUE THREAD

**Issue by abdulghani91** [modularml/max#25]
I tried to download the beta/max, and the downloading finished 100% but the downloaded file (max-x86_64-unknown-linux-gnu-24.1.0-beta1.tar.gz) size is less than the expected size my internet speed is 4 MB. I am using Ubuntu 22.04 on WSL, I tried on Ubuntu 20.04 I got the same problem.

Downloading archive: packages/24.1.0-beta1/max-x86_64-unknown-linux-gnu-24.1.0-beta1.tar.gz
Downloading [ ███████████████████████████████████████████████████████████████████ ] 100%    1.1GiB/1.36GiB @   3.7MiB/s
modular: error: Downloaded archive size does not match expected size:/home/abdulghani/.modular/cache/max-x86_64-unknown-linux-gnu-24.1.0-beta1.tar.gz expected: 1499354208 current size: 1093697792

screenshot from Ubuntu 20.04:

![Max_1](https://github.com/modularml/max/assets/52427956/464fd5f9-6701-44ab-937d-8044fca0055b)
![Max_2](https://github.com/modularml/max/assets/52427956/c9e200ae-7a5a-4d39-96ef-976f938a95ae)
![Max_3](https://github.com/modularml/max/assets/52427956/d71fab6c-bcbe-418e-b8dc-ed60ee7abc01)

**Comment by Ivo-Balbaert** [comment]
I also got this problem the first time I tried the download. The second time, the download went complete. Perhaps a server busy problem.

**Comment by abdulghani91** [comment]
@Ivo-Balbaert I try that for seven-time, and if the server is busy I think the downloading will be very slow. I will try it later and see.

**Comment by iamtimdavis** [comment]
@zbowling can you please take a look?

**Comment by aliahadmd** [comment]
I am having the same problem.
![Screenshot from 2024-02-22 21-06-20](https://github.com/modularml/max/assets/90032081/89173acb-2772-4536-a91f-577fcf57f26c)

**Comment by alexandrnikitin** [comment]
How long does the download process take to the point when you see the error? Is it longer than 5 minutes?

**Comment by zbowling** [comment]
@amscanne

**Comment by abdulghani91** [comment]
@alexandrnikitin 15-20 minutes and the downloaded file has less size the the expected file.
