### ISSUE TITLE
[Docs] Unable to access magic projects, or mojo executable after initial "getting started"  

### ISSUE THREAD

**Issue by russfellows** [modularml/max#251]
### Where is the problem?

https://docs.modular.com/max/tutorials/magic

### What can we do better?

Errors.
After following the initial example, I have never been able to get back into the "hello-world" project again.  Nor was I able to create or use another project.  This after rebooting my Ununtu 20.04 environment.    Here are my commands and output from the shell:

----------------------------------------------------------------------

(base) eval@rtx-4090-1:~$ cd Code/hello-world/
(base) eval@rtx-4090-1:~/Code/hello-world$ ls
hello-world  hello-world.mojo  magic.lock  mojoproject.toml  pixi.toml
(base) eval@rtx-4090-1:~/Code/hello-world$ magic shell
 . "/tmp/pixi_env_0eb.sh"
(base) eval@rtx-4090-1:~/Code/hello-world$  . "/tmp/pixi_env_0eb.sh"
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ mojo --version
Command 'mojo' not found, but can be installed with:
sudo snap install mojo                 # version 1.0.0+601, or
sudo apt  install libmojolicious-perl  # version 9.22+dfsg-1
See 'snap info mojo' for additional versions.
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ magic install
✔ The default environment has been installed.
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ magic ls
✘ No packages found.
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ magic info
     Magic version: 0.4.0
System
------------
      Pixi version: 0.33.0
          Platform: linux-64
  Virtual packages: __unix=0=0
                  : __linux=5.15.153.1=0
                  : __glibc=2.35=0
                  : __cuda=12.5=0
                  : __archspec=1=skylake
         Cache dir: /home/eval/.cache/rattler/cache
      Auth storage: /home/eval/.rattler/credentials.json
  Config locations: No config files found

Global
------------
           Bin dir: /home/eval/.modular/bin
   Environment dir: /home/eval/.modular/envs
      Manifest dir: /home/eval/.modular/manifests/pixi-global.toml

Project
------------
              Name: hello-world
           Version: 0.1.0
     Manifest file: /home/eval/Code/hello-world/pixi.toml
      Last updated: 11-11-2024 16:32:35

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge, https://conda.modular.com/max
  Dependency count: 0
  Target platforms: linux-64

(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$

-------------------------------------------------------------------------

Please note the the "snap" installation of mojo is a completely different executable than Modular's mojo.  

### Anything else?

Errors.
After following initial example, I have never been able to get back into the "hello-world" project again.  Nor was I able to create or use another project.  This after rebooting my Ununtu 20.04 environment.    Here are my commands and output from the shell:

----------------------------------------------------------------------

(base) eval@rtx-4090-1:~$ cd Code/hello-world/
(base) eval@rtx-4090-1:~/Code/hello-world$ ls
hello-world  hello-world.mojo  magic.lock  mojoproject.toml  pixi.toml
(base) eval@rtx-4090-1:~/Code/hello-world$ magic shell
 . "/tmp/pixi_env_0eb.sh"
(base) eval@rtx-4090-1:~/Code/hello-world$  . "/tmp/pixi_env_0eb.sh"
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ mojo --version
Command 'mojo' not found, but can be installed with:
sudo snap install mojo                 # version 1.0.0+601, or
sudo apt  install libmojolicious-perl  # version 9.22+dfsg-1
See 'snap info mojo' for additional versions.
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ magic install
✔ The default environment has been installed.
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ magic ls
✘ No packages found.
(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$ magic info
     Magic version: 0.4.0
System
------------
      Pixi version: 0.33.0
          Platform: linux-64
  Virtual packages: __unix=0=0
                  : __linux=5.15.153.1=0
                  : __glibc=2.35=0
                  : __cuda=12.5=0
                  : __archspec=1=skylake
         Cache dir: /home/eval/.cache/rattler/cache
      Auth storage: /home/eval/.rattler/credentials.json
  Config locations: No config files found

Global
------------
           Bin dir: /home/eval/.modular/bin
   Environment dir: /home/eval/.modular/envs
      Manifest dir: /home/eval/.modular/manifests/pixi-global.toml

Project
------------
              Name: hello-world
           Version: 0.1.0
     Manifest file: /home/eval/Code/hello-world/pixi.toml
      Last updated: 11-11-2024 16:32:35

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge, https://conda.modular.com/max
  Dependency count: 0
  Target platforms: linux-64

(hello-world) (base) eval@rtx-4090-1:~/Code/hello-world$

-------------------------------------------------------------------------

Please note the the "snap" installation of mojo is a completely different executable than Modular's mojo.

**Comment by ehsanmok** [comment]
Thanks for reporting! The minimum Ubuntu version is 22.04 per doc [https://docs.modular.com/max/faq#distribution](https://docs.modular.com/max/faq#distribution)

**Comment by russfellows** [comment]
Hello, I had only one mistake in my problem description, my Ubuntu version IS 22.04, as you may clearly see below.  

Thus, this issue is VERY much relevant.  I will reopen.  See output below:
-----------------------------

eval@rtx-4090-1:~/Code/mandelbrot$ uname -a
Linux rtx-4090-1 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
eval@rtx-4090-1:~/Code/mandelbrot$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
eval@rtx-4090-1:~/Code/mandelbrot$
