### ISSUE TITLE
[Docs] https://docs.modular.com/max/tutorials/magic

### ISSUE THREAD

**Issue by russfellows** [modularml/max#252]
### Where is the problem?

Unable to reactivate / enter a m,agic environment  

### What can we do better?

Please DESCRIBE how to exit, and then re-enter a magic environment.  It is not documented that I can see, and the magic help is of no help.  Theoretically, "magic" is derived from conda.  However, there are no "activate" or deactiavate" commands.  I understand how to switch projects in Conda, you "deactivate" your current env, then "activate" the new one.  No such commands in magic that I see, so how do you manage multiple environments?  This is not documented.

### Anything else?

Please DESCRIBE how to exit, and then re-enter a magic environment.  It is not documented that I can see, and the magic help is of no help.  Supposedly, is derived from conda.  However, there are no "activate" or deactiavate" commands.  

(base) eval@rtx-4090-1:$ cd Code/hello-world/
(base) eval@rtx-4090-1:/Code/hello-world$ ls
hello-world hello-world.mojo magic.lock mojoproject.toml pixi.toml
(base) eval@rtx-4090-1:/Code/hello-world$ magic shell
. "/tmp/pixi_env_0eb.sh"
(base) eval@rtx-4090-1:/Code/hello-world$ . "/tmp/pixi_env_0eb.sh"
(hello-world) (base) eval@rtx-4090-1:/Code/hello-world$ mojo --version
Command 'mojo' not found, but can be installed with:
sudo snap install mojo # version 1.0.0+601, or
sudo apt install libmojolicious-perl # version 9.22+dfsg-1
See 'snap info mojo' for additional versions.
(hello-world) (base) eval@rtx-4090-1:/Code/hello-world$ magic install
✔ The default environment has been installed.
(hello-world) (base) eval@rtx-4090-1:/Code/hello-world$ magic ls
✘ No packages found.
(hello-world) (base) eval@rtx-4090-1:/Code/hello-world$ magic info
Magic version: 0.4.0
System

This IS for Ubuntu 22.04 OS, see below:

eval@rtx-4090-1:/Code/mandelbrot$ uname -a
Linux rtx-4090-1 5.15.153.1-microsoft-standard-WSL2 https://github.com/modularml/max/pull/1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
eval@rtx-4090-1:/Code/mandelbrot$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04.5 LTS
Release: 22.04
Codename: jammy
eval@rtx-4090-1:~/Code/mandelbrot$

**Comment by russfellows** [comment]
Again, this is re-opening problem #251, as I made ONE mistake in the description, which was the OS version, again, this IS Ubuntu 22.04, see above for proof.

**Comment by ehsanmok** [comment]
For local repo / magic project, `magic shell` enters the shell and `exit` exits and it's consistent if you re-enter again because the shell is created once. Note that unlike conda you don't have to use `magic shell` and can run commands via `magic run ...`. Please check out the tutorial esp. this part https://docs.modular.com/max/tutorials/magic#step-2-run-mojo-via-magic
