### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by cp4itech** [modularml/max#254]
### Bug description

Failed when running the scripts in https://docs.modular.com/max/get-started, specifically bash run.sh

### Steps to reproduce

run the command detailed at https://docs.modular.com/max/get-started

curl -ssL https://magic.modular.com/f1a289c9-f284-44f1-865e-e76f1c99ea46 | bash
git clone https://github.com/modularml/max.git
cd max/examples/inference/bert-python-torchscript
magic shell
bash run.sh

Specifically:

  Building wheel for geventhttpclient (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
........
      error: command 'gcc' failed: No such file or directory
      [end of output]

installing gcc made it work (sudo apt install gcc)

IIRC, there was no mention that gcc required. Perhaps worth checking is gcc installed in the install script and suggesting it should be installed for magic to work

### System information

```shell
- What OS did you do install MAX on ?
Ubuntu 22.04.5 LTS

- Provide version information for MAX by pasting the output of max -v`
max 24.5.0 (e8aacb95)
Modular version 24.5.0

- Provide version information for Mojo by pasting the output of mojo -v`
mojo 24.5.0 (e8aacb95)

- Provide Modular CLI version by pasting the output of `modular -v`
N/A
```

**Comment by ehsanmok** [comment]
Thanks for reporting! the requirements are listed [here](https://docs.modular.com/max/faq#what-are-the-system-requirements). We need to link to them at the start as well.

**Comment by bmerkle** [comment]
@ehsanmok is the source for https://docs.modular.com/max/get-started/ not included in any GitHub repo of moudlarml ?
I also had a small improvement but could not find the file get-started.md to create a PR
thanks :-)

**Comment by scottamain** [comment]
> @scottamain is the source for https://docs.modular.com/max/get-started/ not included in any GitHub repo of modularml ? I also had a small improvement but could not find the file get-started.md to create a PR thanks :-)

Hi @bmerkle, no that page is not in the public repo. I would be happy to take your suggestion but that page will actually be obsolete soon. :)

**Comment by bmerkle** [comment]
For the second example (Graph API) please add the missing "magic shell" command after "cd max/examples/graph-api"

For Mojo/max Users this ist obvious but for Users getting started it should be mentioned IMO

Thanks
