### ISSUE TITLE
[BUG]: Install link broken on https://developer.modular.com/home

### ISSUE THREAD

**Issue by stephendwolff** [modularml/max#257]
I clicked 'Install Max' and it tried to open https://docs.modular.com/max/install but fails and redirects to https://docs.modular.com/index

**Comment by scottamain** [comment]
Where did you click "Install MAX"?

**Comment by stephendwolff** [comment]
I visited https://www.modular.com/mojo from LinkedIn, then 
<img width="399" alt="Screenshot 2024-11-27 at 10 57 20" src="https://github.com/user-attachments/assets/3af939c4-9674-4726-8e7a-7ef01b89be93">

Can't find that now, maybe a new site released? but the footer link on the Docs site https://docs.modular.com/ "Install MAX" still links to https://docs.modular.com/max/install

**Comment by stephendwolff** [comment]
Footer link is capitalised as per your "Install MAX", but my link wasn't - it was definitely "Install Max" - as per my screenshot (which i took earlier).

**Comment by stephendwolff** [comment]
@scottamain you've marked it complete - but the footer link is still broken.

**Comment by scottamain** [comment]
Sorry that was automatic by GitHub. Hasn't released yet but the code should have the correct redirect now

**Comment by scottamain** [comment]
The update should take effect in a few minutes.
