### ISSUE TITLE
[Feature Request] add tips to run e.g. yolo sample under WSL (video cam)

### ISSUE THREAD

**Issue by bmerkle** [modularml/max#259]
### What is your request?

I ran the example /max/examples/inference/yolo-python-onnx on a WSL (Windows machine with WSL installed)

Can you add a hint to the documentation about installing a video cam in WSL (and which method is preferred)
I know that this is not a max problem per se, but more a "WSL how to setup video cam" problem.
Nevertheless a small pointer or hint in the documentation would help. 

regarding the information in https://github.com/modularml/max/tree/main/examples/inference/yolo-python-onnx
i think the most promising way is to Install OpenCV in WSL.  sudo apt install python3-opencv
(If you need the camera for development purposes (e.g., machine learning, computer vision), you can use Python's OpenCV library, which supports video streams. OpenCV in WSL can interact with the camera indirectly if it’s accessible via the network.)

### What is your motivation for this change?

I would like to include WSL users also with the possibility to run the max samples 

### Any other details?

Currently the sample fails with the following error:

Skipping ../../models/yolo (already exists)
[ WARN:0@1.630] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.630] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
Webcam was not available.
Falling back to video file segmentation.

Loading and compiling model...

**Comment by ehsanmok** [comment]
Unfortunately this is out of the scope of the tutorial to include video cam installations.
