### ISSUE TITLE
[BUG]: Unable to run magic on non-homebrew machines (MacOS)

### ISSUE THREAD

**Issue by cheemeng** [modularml/max#264]
### Bug description

Unable to run the magic executable after installing magic by using the curl command as per https://docs.modular.com/max/get-started

### Steps to reproduce

First run of magic, and it failed to run:

```
dyld[84849]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <C0459AAA-4D11-3C52-B05D-5CEF8239D6E4> /Users/cheemeng/.modular/bin/magic
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
[1]    84849 abort      magic
```

For context, I use MacPorts instead of Homebrew for package management so shared libraries are in /opt/local/lib.

Running otool -L $(which magic) shows that the path for the liblzma.5.dylib is hardcoded into the executable:
```
otool -L $(which magic)
/Users/cheemeng/.modular/bin/magic:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2503.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1300.120.2)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 61123.121.1)
	/opt/homebrew/opt/xz/lib/liblzma.5.dylib (compatibility version 12.0.0, current version 12.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)

```

Used `install_name_tool` to change the path:
`install_name_tool -change /opt/homebrew/opt/xz/lib/liblzma.5.dylib /opt/local/lib/liblzma.5.dylib  $(which magic)`
which, however, invalidated the executable because it was code-signed.

Temporary workaround: re-sign the executable after that:
`codesign -fs - $(which magic)`

### System information

```shell
- What OS did you do install MAX on ? MacOS Sequoia 15.1.1
```

**Comment by zbowling** [comment]
We just release magic 0.5.1 that should resolve this issue! 

If you need to redownload magic because the self-update feature is busted from this issue you can install it via curl again with `curl -ssL https://magic.modular.com/ | bash`
