### ISSUE TITLE
[BUG]: examples/graph-api/pipelines/weights/download.🔥 does not check the downloaded file

### ISSUE THREAD

**Issue by lesoup-mxd** [modularml/max#265]
### Bug description

When a run script from examples calls download.🔥, if getting a network interrupt, the stream cuts, and the download.🔥 successfully returns a malformed cache model. The inference still runs it, and we end up with garbage output, since the model uses incorrect weights.

### Steps to reproduce

- git clone https://github.com/modularml/max.git
- cd max/examples/graph-api/pipelines
- magic run llama3 --prompt "Why is the sky blue?"
- interrupt the network

### System information

```shell
Linux 6.12 kernel, GNU Linker, Arch Linux (rolling)
- Generally this info should be irrelevant here
```

**Comment by BradLarson** [comment]
This has been fixed in the 24.6 release, where we now use `huggingface_hub` to download weights and re-start downloads if they were interrupted.
