### ISSUE TITLE
[BUG]: Stable Diffusion Inference demo, Runway is gone from huggingface.

### ISSUE THREAD

**Issue by CodeAlexx** [modularml/max#268]
### Bug description

The stable diffusuon demo uses https://huggingface.co/runwayml/stable-diffusion-v1-5, it was taken down about 6 months ago. can you please update the code to use another more current one like sdxl? 1.5 is 2 years old or older and just old technology

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install MAX on ?
- Provide version information for MAX by pasting the output of max -v`
- Provide version information for Mojo by pasting the output of mojo -v`
- Provide Magic CLI version by pasting the output of `magic -v`
```

**Comment by ehsanmok** [comment]
Thanks! The python example is using our own copy [modularai/stable-diffusion-1.5-onnx](https://huggingface.co/modularai/stable-diffusion-1.5-onnx). Note that all the examples in the `examples` subrepo aren't using GPU and are CPU only which is pre v24.6. We'll soon revamp/remove them and our priorities are in LLM and VLLM in the `pipelines/python` sub-repo.  If you've needs for such Stable Diffusion models please reach out [here](https://www.modular.com/enterprise#form) and we'd love to help out.
