### ISSUE TITLE
[Docs] Why is the `nvidia/cuda` base container used for the MAX container?

### ISSUE THREAD

**Issue by benz0li** [modularml/max#273]
### Where is the problem?

https://docs.modular.com/max/container/#container-contents

### What can we do better?

PyTorch installs its own CUDA runtime (incl. required CUDA binaries/libraries).

There is no need for the [`nvidia/cuda`](https://hub.docker.com/r/nvidia/cuda) base container, which also includes the CUDA runtime (cudart).

Cross reference:

* https://github.com/iot-salzburg/gpu-jupyter/issues/153#issuecomment-2440653300 ff

### Anything else?

IMHO you could simply use the \[official\] Docker [python:3.12](https://hub.docker.com/_/python) image.

@ehsanmok Or does MAX itself somehow depend on the CUDA runtime?

**Comment by benz0li** [comment]
@ehsanmok Currently, there is no GPU acceleration for MAX w/o PyTorch. Correct?

**Comment by benz0li** [comment]
Although the MAX container is based on the NVIDIA CUDA Deep Learning Container [version 12.5.0 base Ubuntu 22.04](https://hub.docker.com/layers/nvidia/cuda/12.5.0-base-ubuntu22.04/images/sha256-e58b22698c6f468de4dd32578d40821e30eae77251e18713ef986576d08ea825), PyTorch does not use the container's 12.5 CUDA runtime but its own 12.1 CUDA runtime:

```
docker run --rm -ti \
  --runtime nvidia \
  --gpus all \
  --entrypoint '' \       
  modular/max-openai-api:24.6.0 bash -c \
  'nvidia-smi \
    && python -c "import torch; print(torch.version.cuda)"'
```

```
Fri Dec 20 10:38:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.216.01             Driver Version: 535.216.01   CUDA Version: 12.5     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 4000                On  | 00000000:AF:00.0 Off |                  N/A |
| 30%   42C    P8               9W / 125W |      1MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
12.1
```

**Comment by ehsanmok** [comment]
For 24.6, we provide [modular/max-openai-api:24.6.0](https://registry.hub.docker.com/r/modular/max-openai-api) docker image as a [generic base MAX container](https://docs.modular.com/max/container). This is meant to serve / run models such as

* Llama3 written using our MAX Graph API ([see the list of the supported models](https://github.com/modularml/max/tree/main/pipelines/python#pipelines))
* as well as models that we don't have MAX Graph implementation equivalent yet ([see the list here](https://github.com/modularml/max/tree/main/pipelines/python#verified-hugging-face-model-architectures)) and allow serving them through MAX Serve in torch eager mode now. Check [this tutorial](https://docs.modular.com/max/tutorials/deploy-pytorch-llm) for those PyTorch model.

As a result we include NVIDIA runtime only for those compatible models that we don't have MAX Graph API implementation to make the image generic. 

In the next release, this will change and we plan to split up the docker image and provide a more specialized image for our MAX Graph API implementations which would be lighter weight as for example on NVIDIA GPUs, we only require NVIDIA Driver and nothing else so the specialized image won't include those unused NVIDIA runtime libs.

**Comment by benz0li** [comment]
> we include NVIDIA runtime only for those compatible models that we don't have MAX Graph API implementation to make the image generic.

Got it.

Happy holidays!

**Comment by ehsanmok** [comment]
Agree! we'll optimize that and get rid unnecessary dependencies in the next release.
Happy holidays :)

**Comment by benz0li** [comment]
I will continue to maintain both a [CUDA-based MAX docker stack](https://github.com/b-data/mojo-docker-stack/blob/main/CUDA.md) and a [CUDA-based JupyterLab MAX docker stack](https://github.com/b-data/jupyterlab-mojo-docker-stack/blob/main/CUDA.md).  
👉 Just in case someone wants to build upon these and install packages from NVIDIA's APT repository.

**Comment by ehsanmok** [comment]
Looks awesome! thanks for maintaining them.

**Comment by benz0li** [comment]
> Looks awesome! thanks for maintaining them.

There is more:

* [(CUDA-based) Data Science dev containers](https://github.com/b-data/data-science-devcontainers)
  * https://github.com/modularml/mojo/discussions/2648
* [Mojo dev container](https://github.com/benz0li/mojo-dev-container)
  * https://github.com/modularml/mojo/discussions/2819
  * https://github.com/modularml/mojo/pull/2664
