### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by jrozentur** [modularml/max#276]
### Where is the problem?

https://docs.modular.com/max/tutorials/magic

### What can we do better?

Installation does not work as described. Resulting myproject.toml contains reference to conda channel https://conda.modular.com/max which does not seem to exist
magic init hello-magic --format mojoproject
Created /mojo_perm/hello-magic/mojoproject.toml
⠉ updating lock-file   [00:00:20] [────────────────────────────────────────]    0/2                                                                                           
  ⠁ default:linux-64     [00:00:20] resolving conda                                                                                                                           Killed

If I remove the channel, but keep conda-forge it installs packages using conda just fine (but then no max of course)

### Anything else?

You should provide a simplified installation or docker to try things out. Path to "hello world" has become more complicated with magic

**Comment by ehsanmok** [comment]
Thanks for reporting! I can't reproduce the error. The MAX conda channel is necessary. What `magic --version` are you using? could you `rm -r hello-magic` and try again? (run `magic clean` just in case if there's a stale dependency).

For a better context, magic CLI is mostly orthogonal to docker. It's very much like Rust's cargo or Node npm in environment and package management and multi-platform support. If interested, we have a blog on [why magic?](https://www.modular.com/blog/why-magic)

**Comment by jrozentur** [comment]
This is because 'magic init' runs out of memory. My docker compose file  had
deploy:
  resources:
    limits:
      memory: *1G*
Apparently 1G this is not enough. Docker engine has 8gb total, and that is
enough and it works when limit is removed

Why it needs that much memory to init a project is unclear. I could install
anaconda and add mojo into that same container, using instructions at
https://docs.modular.com/magic/conda:

conda create -n max-project -c conda-forge -c https://conda.modular.com/max/
\

  python=3.11 max=* -y


However, running mojo gives errors:

 conda activate max-project
(max-project) ***@***.***:/tmp/mojo4# mojo --version
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
(required by mojo)
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found
(required by mojo)
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found
(required by mojo)
mojo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found
(required by
/root/anaconda3/envs/max-project/bin/../lib/libAsyncRTRuntimeGlobals.so)


My base docker has image ubuntu:20.04; running with modular/max-opanai-api
does not have this issue

**Comment by ehsanmok** [comment]
Please check the [system requirements](https://docs.modular.com/max/faq/#system-requirements) which requires at least 8GB memory and reopen it if it's still the issue.
