### ISSUE TITLE
 No module named 'max'

### ISSUE THREAD

**Issue by abdulghani91** [modularml/max#29]
I followed the instructions for installing any running max [Modular](https://docs.beta.modular.com/engine/get-started/?_hsmi=295007896), but when I run `bash run.sh` I got `ModuleNotFoundError: No module named 'max'`

full error: ./....../max/examples/inference/roberta-python-tensorflow/simple-inference.py", line 24, in <module>
    from max import engine

I tried to run max and I get:

Command 'max' not found, did you mean:
  command 'nax' from snap nax (0.0.35)
  command 'mcx' from deb mcl (1:14-137+ds-9build2)
  command 'pax' from deb pax (1:20201030-1build2)
  command 'mtx' from deb mtx (1.3.12-14build2)
  command 'mag' from deb texlive-binaries (2021.20210626.59705-1ubuntu0.1)
  command 'fax' from deb efax (1:0.9a-20)
  command 'mix' from deb elixir (1.12.2.dfsg-2.2)
  command 'maq' from deb maq (0.7.1-9)
  command 'mex' from deb texlive-lang-polish (2021.20220204-1)
  command 'vax' from deb simh (3.8.1-6.1)
  command 'mad' from deb mmv (1.01b-19build1)
  command 'man' from deb man-db (2.10.2-1)
See 'snap info <snapname>' for additional versions.

I am using Ubuntu 22.04 with WSL
Python 3.10
<img width="663" alt="Screenshot_2" src="https://github.com/modularml/max/assets/52427956/07f08178-ca93-423a-a505-a15985de57e8">

Did I have to add max to the path environment or anything else?

**Comment by abdulghani91** [comment]
@katelyncaldwell Hi I try this command:
`python3 -m pip install --find-links "$(modular config max.path)/wheels" max-engine` and I got:


python3 -m pip install --find-links "$(modular config max.path)/wheels" max-engin-9)
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /home/abdulghani/.modular/pkg/packages.modular.com_beta_max/wheels
ERROR: Could not find a version that satisfies the requirement max-engin (from versions: none)
ERROR: No matching distribution found for max-engin

Did I have to add anything to the modular config?

**Comment by goldiegadde** [comment]
@abdulghani91 that command should work, 
python3 -m pip install --find-links /home/ubuntu/.modular/pkg/packages.modular.com_beta_max/wheels max-engine

and you should run these commands, to set the max path. 

BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
echo 'export MODULAR_HOME="/home/ubuntu/.modular"' >> "$BASHRC"
echo 'export PATH="/home/ubuntu/.modular/pkg/packages.modular.com_beta_max/bin:$PATH"' >> "$BASHRC"
source "$BASHRC"


In your error message above 
`ERROR: Could not find a version that satisfies the requirement max-engin (from versions: none)`
I see the e missing from max-engine, is that a copy paste error, or a real error ?

Can you try `modular uninstall beta/max` and try to install this one more time ?
All the commands I listed above can be seen in the post-install message

**Comment by abdulghani91** [comment]
@goldiegadde You were right I miss the last letter e in engine. Yes, the command works fine, and thank you for the command to set the max path in the environment.

**Comment by goldiegadde** [comment]
Awesome, I will close this ticket now @abdulghani91 , feel free to reopen if you still have trouble installing.
