### ISSUE TITLE
[BUG]: won't install on MBP M3 max

### ISSUE THREAD

**Issue by mikeseven** [modularml/max#69]
### Bug description

fresh modular install, brew upgraded to latest packages
on macbook pro M3 Max.
`modular install max` can't find packages for this hardware????

(yes I know it's linux only for now but hopefully Max will be on Mac soon)

### Steps to reproduce

modular install max
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/max with your hardware information

### System information

```shell
modular host-info
  Host Information
  ================

  Target Triple: aarch64-unknown-macosx
  CPU: apple-m1
  CPU Features: aes, complxnum, crc, dotprod, fp-armv8, fp16fml, fullfp16, jsconv, lse, neon, pauth, ras, rcpc, rdm, sha2, sha3
```

**Comment by ehsanmok** [comment]
Please check out the [requirements](https://docs.modular.com/engine/get-started#requirements) for this preview release. We don't support MacOS now.

**Comment by mikeseven** [comment]
Yes I know.
Luckily, it works on docker for aarch64, impressive work!
when is it going to be supported for mac?
