### ISSUE TITLE
[Feature Request] Can we get a Docker Image

### ISSUE THREAD

**Issue by sungkim11** [modularml/max#74]
### What is your request?

Request for a Docker image

### What is your motivation for this change?

Install is too complex and involved

**Comment by sungkim11** [comment]
I was mistaken. There is already a docker image.

**Comment by antonl321** [comment]
could you point to it please?

**Comment by ehsanmok** [comment]
You can pull from the public ECR `public.ecr.aws/modular/max-serving-de`. I'll reopen to include it in README as well.

**Comment by ehsanmok** [comment]
Addressed in #93
