### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by kittupriyatham** [modularml/max#75]
### Issue description

Cannot install other modular packages. Looks like a bug in the install script. It shows the following error at the end: "Error: Command '['/home/kittupriyatham/.modular/pkg/packages.modular.com_max/venv/bin/python3', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1."

### Steps to reproduce

Update the modular if not done, then
write any install command like `modular install max`.
The above error appears.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?

modular 0.5.1 (1b608e3d)
Microsoft Windows 11 WSL 2 Ubuntu 22.04.3
```

**Comment by kittupriyatham** [comment]
Dear maintainers, I understand where the problem is, and I would like to fix the issue. Please grant me access to the codebase; I am committed to NDA.

**Comment by ehsanmok** [comment]
We're here to help :) the issue is we current don't support windows. Please check out the [requirements](https://docs.modular.com/engine/get-started/#requirements).

**Comment by kittupriyatham** [comment]
hi @ehsanmok, 
Thanks for replying.
But the issue is coming in wsl.
Windows Subsystem for Linux and same install issue is coming for mojo too.

**Comment by ehsanmok** [comment]
That is unfortunately untested right now. We'll update on that. Thanks!

**Comment by kittupriyatham** [comment]
I would like to join your team. I have applied through the careers page.

**Comment by kittupriyatham** [comment]
Always. :) 
Oh, I see. Thanks for informing @ehsanmok 
Looking forward to the update from you.
