### ISSUE TITLE
[BUG]: Could not install modular MAX on M3 Max

### ISSUE THREAD

**Issue by chiumichael** [modularml/max#77]
### Bug description

Could not install modular MAX on my m3 max.

Output from `uname -a` if that helps

root:xnu-10002.81.5~7/RELEASE_ARM64_T6031 arm64

### Steps to reproduce

`modular install max` on a m3 max

### System information

```shell
- What OS did you do install MAX on ?

`macos 14.3.1

- Please run `modular host-info`

  
Host Information
  ================

  Target Triple: aarch64-unknown-macosx
  CPU: apple-m1
  CPU Features: aes, complxnum, crc, dotprod, fp-armv8, fp16fml, fullfp16, jsconv, lse, neon, pauth, ras, rcpc, rdm, sha2, sha3
```

- Provide Modular CLI version by pasting the output of `modular -v`

`modular 0.5.1 (1b608e3d)`

**Comment by ehsanmok** [comment]
Please check out the [requirements](https://docs.modular.com/engine/get-started#requirements) for this preview release. We don't support MacOS now.
