### ISSUE TITLE
[BUG]: MAX significantly slower than tensor flow 

### ISSUE THREAD

**Issue by antonl321** [modularml/max#79]
### Bug description

I followed the "Get started" guide, the performance test shows that MAX is markedly slower that tensor flow.  

### Steps to reproduce

- repeated twice, got close values in both runs.

![image](https://github.com/modularml/max/assets/52708870/da6ddb11-f389-462b-8ab1-117fca983b9b)

-

### System information

```shell
- What OS did you do install MAX on ?
CPU: 13th Gen Intel(R) Core(TM) i7-13700H
Arch: X86_64
Clock speed: 2.9184 GHz
Cores: 20
- Provide version information for MAX by pasting the output of max -v`
max 24.1.0 (c176f84d)
Modular version 24.1.0-c176f84d-release
- Provide version information for Mojo by pasting the output of mojo -v`
mojo 24.1.0 (c176f84d)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.5.1 (1b608e3d)
```

**Comment by iamtimdavis** [comment]
Thanks @antonl321. We have not optimized for laptops with mixed P/E cores at this stage, and its something we'll add to our [Sharp Edges](https://docs.modular.com/max/roadmap) document @scottamain as FYI.

Please try another machine if you can as we've primarily focused on X86 Data Center hardware! You can see from our [Performance Dashboard](https://performance.modular.com/). Thank you!

**Comment by scottamain** [comment]
Just to help others who might find this, we now explain this behavior in our FAQ:
https://docs.modular.com/engine/faq#why-does-max-engine-perform-slowly-on-my-computer-compared-to-pytorch-or-tensorflow
