### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by belcom1** [modularml/max#89]
Modular CLI cannot be installed from the Ubuntu terminal.
Modular CLI cannot be installed from the Ubuntu terminal.
In the installation command text box, type "curl https://get.modular.com | sh -
modular auth "I installed it with sudo like this, but only Mojo cannot be installed.

**Comment by iamtimdavis** [comment]
Please see my comment in #90. 

Also FYI - @belcom1  we'd appreciate if you don't re-open multiple issues on the same thing, you can just open 1 issue and we'll get back to you. Thanks!
