### ISSUE TITLE
The module is not completely installed, so counterfeit module installation is not possible.

### ISSUE THREAD

**Issue by belcom1** [modularml/max#90]
![20240303_113809](https://github.com/modularml/max/assets/67812249/0c96a88c-f1bb-4793-ba0f-54de185880e0)

**Comment by iamtimdavis** [comment]
Thanks @belcom1 - these are the instructions to install Mojo as a standalone package. Given you filed this in the MAX repo, if you Install MAX [via this link](https://docs.modular.com/engine/get-started/) - Mojo is included, you don't need a standalone installation of it. You can read about [MAX + Mojo here](https://www.modular.com/blog/max-is-here-what-does-that-mean-for-mojo).

Separately, we'll breakout this step for dedicated installations of Mojo as a UI fix @robert-j-webb

**Comment by belcom1** [comment]
Yes, that's right. I copied it from Chrome and installed it on Ubuntu. The mojo module cannot be installed because it is not fully installed.

**Comment by belcom1** [comment]
![1](https://github.com/modularml/max/assets/67812249/47c8985e-65c1-445f-b135-da208c3cc7b0)

**Comment by belcom1** [comment]
![2](https://github.com/modularml/max/assets/67812249/39c9e610-13d7-4850-bf30-a65ce91e190a)

**Comment by belcom1** [comment]
![3](https://github.com/modularml/max/assets/67812249/9a2002e0-fdf7-40bd-acc2-27f0e1112553)

**Comment by amscanne** [comment]
@belcom1 did you visit the URL [above](https://github.com/modularml/max/issues/90#issuecomment-1976231985) and see any issues? (After running `modular auth` with no arguments.)

I think the crashpad issue is separate and perhaps misleading in this case. By any chance are you running WSL1? (https://github.com/modularml/mojo/issues/984)
