### ISSUE TITLE
[BUG]: 저의 싸이트에  우분투 터미널에서는 모듈식 CLI를 설치 박스 내용이 맞나요?

### ISSUE THREAD

**Issue by belcom1** [modularml/max#91]
![20240303_120928](https://github.com/modularml/max/assets/67812249/742ed0b1-1e9b-4d0e-9601-f790b8ee6438)
Is the contents of the modular CLI installation box on my site in the Ubuntu terminal correct?

**Comment by iamtimdavis** [comment]
Please see my response in #90. Thanks!
